import Link from "next/link";
import { notFound } from "next/navigation";
import DashboardShell from "@/components/DashboardShell";
import InviteProspectForm from "@/components/InviteProspectForm";
import NavigationTrail from "@/components/NavigationTrail";
import { addRequestClarificationAction, updateServiceRequestStatusAction } from "@/app/request-actions";
import { assignRequestAction } from "@/app/staff-actions";
import { createRevisionDraftAction, rollbackRevisionAction } from "@/app/revision-actions";
import { requireUser } from "@/lib/auth";
import { hasCapability } from "@/lib/capabilities";
import { getBusinessById } from "@/lib/db";
import { presentRequestEvent } from "@/lib/request-presentation";
import { REVIEW_REQUEST_STATUSES } from "@/lib/request-domain";
import { canAccessRequest, getRequestDetail } from "@/lib/request-sqlite";
import { listTeamMemberChoices } from "@/lib/scalable-queries";
import { listContentRevisions } from "@/lib/revision-service";

export const dynamic = "force-dynamic";

export default async function RequestDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; created?: string; assigned?:string; clarified?:string; published?:string; rolledBack?:string; error?: string; staffQ?: string }> }) {
  const user = await requireUser();
  const requestId = Number.parseInt((await params).id, 10);
  const query = await searchParams;
  if (!Number.isInteger(requestId)) notFound();
  const request = getRequestDetail(requestId);
  if (!request) notFound();
  if (!canAccessRequest(user, request)) notFound();
  const manager = hasCapability(user, "operations:manage");
  const teamMember = user.access_role === "team_member";
  const client = user.access_role === "client";
  const businessId = !manager ? request.business_id : null;
  const business = !manager && businessId ? getBusinessById(businessId) || null : null;
  const teamMembers = manager
    ? listTeamMemberChoices(query.staffQ, request.assigned_user_id)
    : [];
  const revisions = request.business_id ? listContentRevisions(request.id) : [];
  const clarifications=request.events.filter((event)=>event.event_type==="client_clarification"||event.event_type==="staff_clarification");
  const history=request.events.filter((event)=>event.event_type!=="client_clarification"&&event.event_type!=="staff_clarification");
  const clarificationOpen=!["published","completed","rejected","cancelled"].includes(request.status);
  return <DashboardShell user={user} business={business}>
    <NavigationTrail items={[{label:manager?"Operations":teamMember?"Assigned requests":"My requests",href:"/dashboard/requests"},{label:request.public_ref}]} fallback="/dashboard/requests"/>
    <div className="dashboard-head"><div><h1>{request.public_ref}</h1><p>{request.request_type} request received {new Date(request.created_at).toLocaleString()}</p></div><span className={`badge ${request.status}`}>{request.status.replaceAll("_", " ")}</span></div>
    {query.created && <p className="notice">{query.created === "manager" ? "The request was recorded on behalf of the client." : "Your request was sent to SuqPage."}</p>}{query.saved && <p className="notice">Request status updated.</p>}{query.assigned && <p className="notice">Assignment updated.</p>}{query.clarified && <p className="notice">Clarification message added.</p>}{"published" in query && <p className="notice">The approved revision is now live.</p>}{"rolledBack" in query && <p className="notice">The retained catalog version was restored as a new live version.</p>}{query.error && <p className="error">{query.error==="clarification"?"The clarification message could not be added.":query.error}</p>}
    <div className="split"><section className="panel"><h2>Client instruction</h2><dl className="request-facts"><dt>Contact name</dt><dd>{request.contact_name}</dd><dt>Contact</dt><dd>{request.contact_value}</dd><dt>Business</dt><dd>{request.business_display_name || request.business_name || "Not provided"}</dd><dt>Submitted by</dt><dd>{request.submitter_kind === "manager" ? "SuqPage for client" : request.submitter_kind}</dd>{request.assigned_user_name && !client ? <><dt>Assigned to</dt><dd>{request.assigned_user_name}</dd></> : null}</dl><h3>Original request</h3><p className="request-copy">{request.request_text}</p></section>{manager || teamMember ? <section className="panel"><h2>Work status</h2><form action={updateServiceRequestStatusAction} className="form-grid"><input type="hidden" name="requestId" value={request.id}/><div className="field full"><label htmlFor="request-status">Status</label><select id="request-status" name="status" defaultValue={request.status}>{REVIEW_REQUEST_STATUSES.map((status) => <option value={status} key={status}>{status.replaceAll("_"," ")}</option>)}</select></div><div className="field full"><button className="btn">Update status</button></div></form><p><small>Use Private revisions for structured work. Current live data cannot be edited here.</small></p></section> : <section className="panel"><h2>What happens next</h2><p>SuqPage reviews your instruction, asks for clarification if needed, and prepares private work for your approval. Nothing is published from this request without your approval.</p></section>}</div>
    {manager ? <section className="panel"><h2>Team assignment</h2><form className="collection-toolbar" action={`/dashboard/requests/${request.id}`} method="get"><label className="collection-search"><span>Find a team member</span><input name="staffQ" type="search" defaultValue={query.staffQ || ""} maxLength={120} placeholder="Name or email"/></label><button className="small-btn">Search staff</button></form><form action={assignRequestAction} className="form-grid"><input type="hidden" name="requestId" value={request.id}/><div className="field full"><label htmlFor="request-assignee">Assigned team member</label><select id="request-assignee" name="teamMemberId" defaultValue={request.assigned_user_id || ""}><option value="">Unassigned</option>{teamMembers.map((member)=><option key={member.id} value={member.id}>{member.name} · {member.email}</option>)}</select><small>Showing at most 20 matching team members. Search to narrow a larger team.</small></div><div className="field full"><button className="btn">Save assignment</button></div></form></section> : null}
    {request.business_id ? <section className="panel"><div className="dashboard-head"><div><h2>Private revisions</h2><p>Numbered previews stay separate from the live showroom until exact client approval and manager publication.</p></div>{(manager||teamMember)&&!revisions.some((revision)=>revision.status==="draft")?<form action={createRevisionDraftAction}><input type="hidden" name="requestId" value={request.id}/><button className="btn brand">{revisions.length?"Create next recipe":"Prepare first recipe"}</button></form>:null}</div>{revisions.length?<div className="request-card-list">{revisions.map((revision)=><div className="staff-card" key={revision.id}><div><strong>Revision {revision.revision_number}</strong><span>Base live version {revision.base_content_version}{revision.published_content_version?` · published as ${revision.published_content_version}`:""}</span></div><span className={`badge ${revision.status}`}>{revision.status.replaceAll("_"," ")}</span><div className="inline-actions">{revision.status==="draft"?(manager||teamMember)?<><Link className="small-btn" href={`/dashboard/requests/${request.id}/revisions/${revision.id}/studio`}>Open recipe studio</Link>{manager?<Link className="small-btn" href={`/dashboard/requests/${request.id}/revisions/${revision.id}/edit`}>Recovery editor</Link>:null}</>:<span className="muted">SuqPage is preparing this revision.</span>:<Link className="small-btn" href={`/dashboard/requests/${request.id}/revisions/${revision.id}/preview`}>View preview</Link>}{manager&&revision.status==="published"?<form action={rollbackRevisionAction}><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="businessId" value={revision.business_id}/><input type="hidden" name="targetVersion" value={revision.base_content_version}/><button className="small-btn danger">Rollback to version {revision.base_content_version}</button></form>:null}</div></div>)}</div>:<div className="empty-state">No private revision has been prepared yet.</div>}</section>:null}
    {manager && request.request_type === "onboarding" && ["public","manager"].includes(request.submitter_kind) && !request.represented_client_user_id ? <section className="panel"><h2>{request.business_id ? "Replace client invitation" : "Accept prospect and invite client"}</h2><p>Create a draft tenant and a single-use account invitation. The raw link appears once and expires after 72 hours.</p><InviteProspectForm requestId={request.id} clientName={request.contact_name} businessName={request.business_display_name || request.business_name} email={request.contact_value}/></section> : null}
    {request.submitter_kind !== "public" && <section className="panel"><h2>Private reference images</h2>{request.attachments.length ? <div className="request-image-grid">{request.attachments.map((attachment) => <figure key={attachment.id}><img src={`/api/requests/${request.id}/attachments/${attachment.id}`} alt={attachment.original_name}/><figcaption>{attachment.original_name} · {attachment.width}×{attachment.height}</figcaption></figure>)}</div> : <div className="empty-state">Reference photography has not been supplied yet. The AI blueprint can create labeled upload slots after it chooses the page structure.</div>}</section>}
    <section className="panel"><h2>Clarifications</h2>{clarifications.length?<ol className="request-events">{clarifications.map((event)=>{const own=event.actor_user_id===user.id;const label=user.access_role==="client"?(event.actor_access_role==="client"?(own?"You":"Client"):"SuqPage team"):(event.actor_name||"SuqPage team");return <li key={event.id}><strong>{label}</strong><span>{event.detail}</span><time>{new Date(event.created_at).toLocaleString()}</time></li>})}</ol>:<div className="empty-state">No clarification messages yet.</div>}{clarificationOpen?<form action={addRequestClarificationAction} className="form-grid"><input type="hidden" name="requestId" value={request.id}/><div className="field full"><label htmlFor="clarification-message">{user.access_role==="client"?"Reply to SuqPage":"Ask or answer a clarification"}</label><textarea id="clarification-message" name="message" required maxLength={2000} placeholder="Add information without changing the original request."/></div><div className="field full"><button className="btn">Add clarification</button></div></form>:null}</section>
    <section className="panel"><h2>Request history</h2><ol className="request-events">{history.map((event) => { const presented = presentRequestEvent(event, client); return <li key={event.id}><strong>{presented.label}</strong><span>{presented.detail}</span><time>{new Date(event.created_at).toLocaleString()}</time></li>; })}</ol></section>
  </DashboardShell>;
}
