"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { audit, cleanText } from "@/lib/security";
import { createDraftRevision, decideRevision, publishApprovedRevision, rollbackCatalogVersion, saveDraftRevision, submitRevisionForReview } from "@/lib/revision-service";
import { RevisionError } from "@/lib/revision-domain";

const number=(formData:FormData,key:string)=>Number.parseInt(cleanText(formData.get(key),20),10);
const failure=(requestId:number,message:string):never=>redirect(`/dashboard/requests/${requestId}?error=${encodeURIComponent(message)}`);

export async function createRevisionDraftAction(formData:FormData){const user=await requireUser();const requestId=number(formData,"requestId");let revisionId:number|null=null;try{revisionId=createDraftRevision(user,requestId).id;}catch(error){failure(requestId,error instanceof RevisionError?error.message:"The revision could not be created.");}if(!revisionId)failure(requestId,"The revision could not be created.");redirect(`/dashboard/requests/${requestId}/revisions/${revisionId}/edit`);}
export async function saveRevisionDraftAction(formData:FormData){const user=await requireUser();const requestId=number(formData,"requestId"),revisionId=number(formData,"revisionId");try{saveDraftRevision(user,revisionId,formData.get("snapshot"),formData.get("summary"));audit("revision.draft_saved",{userId:user.id,detail:{requestId,revisionId}});}catch(error){redirect(`/dashboard/requests/${requestId}/revisions/${revisionId}/edit?error=${encodeURIComponent(error instanceof RevisionError?error.message:"The draft could not be saved.")}`);}revalidatePath(`/dashboard/requests/${requestId}`);redirect(`/dashboard/requests/${requestId}/revisions/${revisionId}/edit?saved=1`);}
export async function submitRevisionAction(formData:FormData){const user=await requireUser();const requestId=number(formData,"requestId"),revisionId=number(formData,"revisionId");try{submitRevisionForReview(user,revisionId);audit("revision.submitted",{userId:user.id,detail:{requestId,revisionId}});}catch(error){failure(requestId,error instanceof RevisionError?error.message:"The revision could not be submitted.");}revalidatePath(`/dashboard/requests/${requestId}`);redirect(`/dashboard/requests/${requestId}/revisions/${revisionId}/preview?submitted=1`);}
export async function decideRevisionAction(formData:FormData){const user=await requireUser();const requestId=number(formData,"requestId"),revisionId=number(formData,"revisionId");const value=cleanText(formData.get("decision"),20);if(value!=="approve"&&value!=="reject")failure(requestId,"Choose approve or reject.");const decision=value as "approve"|"reject";try{decideRevision(user,revisionId,decision,formData.get("comment"));audit(decision==="approve"?"revision.approved":"revision.rejected",{userId:user.id,businessId:user.business_id,detail:{requestId,revisionId}});}catch(error){redirect(`/dashboard/requests/${requestId}/revisions/${revisionId}/preview?error=${encodeURIComponent(error instanceof RevisionError?error.message:"The decision could not be saved.")}`);}revalidatePath(`/dashboard/requests/${requestId}`);redirect(`/dashboard/requests/${requestId}/revisions/${revisionId}/preview?decided=${decision}`);}
export async function publishRevisionAction(formData:FormData){const user=await requireUser();const requestId=number(formData,"requestId"),revisionId=number(formData,"revisionId");try{const result=publishApprovedRevision(user,revisionId);audit("revision.published",{userId:user.id,businessId:result.businessId,detail:{requestId,revisionId,contentVersion:result.contentVersion}});}catch(error){failure(requestId,error instanceof RevisionError?error.message:"The approved revision could not be published.");}revalidatePath("/");revalidatePath(`/dashboard/requests/${requestId}`);redirect(`/dashboard/requests/${requestId}?published=1`);}
export async function rollbackRevisionAction(formData:FormData){const user=await requireUser();const requestId=number(formData,"requestId"),businessId=number(formData,"businessId"),targetVersion=number(formData,"targetVersion");try{const result=rollbackCatalogVersion(user,businessId,targetVersion);audit("catalog.rolled_back",{userId:user.id,businessId,detail:{targetVersion,newContentVersion:result.contentVersion}});}catch(error){failure(requestId,error instanceof RevisionError?error.message:"The rollback could not be completed.");}revalidatePath("/");redirect(`/dashboard/requests/${requestId}?rolledBack=1`);}
