"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import type { Business } from "@/lib/types";

const industries:Record<string,string>={alhayabrand:"Fashion, Textiles & Accessories",usashopet:"Beauty, Wellness & Natural Medicine",novatech:"Electronics & Appliances",homevibe:"Home, Furniture & Living"};
const categories:Record<string,string>={alhayabrand:"Modest fashion",usashopet:"Beauty & wellness",novatech:"Technology",homevibe:"Home & living"};
export default function ShowroomDirectory({businesses,previews}:{businesses:Business[];previews:Record<string,string>}){const [query,setQuery]=useState(""),[category,setCategory]=useState("all"),[industry,setIndustry]=useState("all"),[sort,setSort]=useState("name");const results=useMemo(()=>{const q=query.trim().toLowerCase();return businesses.filter(b=>(category==="all"||categories[b.handle]===category)&&(industry==="all"||industries[b.handle]===industry)&&(!q||`${b.name} ${b.handle} ${b.tagline} ${categories[b.handle]||""} ${industries[b.handle]||""}`.toLowerCase().includes(q))).sort((a,b)=>sort==="handle"?a.handle.localeCompare(b.handle):a.name.localeCompare(b.name))},[businesses,category,industry,query,sort]);const categoryOptions=[...new Set(Object.values(categories))],industryOptions=[...new Set(Object.values(industries))];return <div><div className="directory-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by name, /@handle, product, or category" aria-label="Search showrooms"/><div className="directory-selects"><label><span>Category</span><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Category selector"><option value="all">All Categories</option>{categoryOptions.map(label=><option key={label} value={label}>{label}</option>)}</select></label><label><span>Industry</span><select value={industry} onChange={e=>setIndustry(e.target.value)} aria-label="Industry selector"><option value="all">All Industries</option>{industryOptions.map(label=><option key={label} value={label}>{label}</option>)}</select></label><label><span>Sort</span><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort selector"><option value="name">Sort by name</option><option value="handle">Sort by handle</option></select></label><button className="small-btn" onClick={()=>{setCategory("all");setIndustry("all");setQuery("");setSort("name")}}>View all showrooms</button></div><div className="directory-filters"><button className={category==="all"&&industry==="all"&&!query?"active":""} onClick={()=>{setCategory("all");setIndustry("all");setQuery("")}}>All businesses</button>{categoryOptions.map(label=><button key={label} className={category===label?"active":""} onClick={()=>setCategory(category===label?"all":label)}>{label}</button>)}</div></div>{results.length?<div className="showroom-grid">{results.map(b=><Link key={b.id} className="showroom-card" href={`/@${b.handle}`}><Image src={previews[b.handle]||b.hero_image_path} alt={`${b.name} showroom`} width={900} height={506}/><div><span className="eyebrow">{industries[b.handle]||"Business"}</span><h3>{b.name}</h3><p><strong>/@{b.handle}</strong></p><p>{b.tagline}</p><strong>Open showroom →</strong></div></Link>)}</div>:<div className="directory-empty">No showrooms match that search.</div>}</div>}
