import type { DenseDemoOfferingKind } from "./dense-demo-seed";
import type { SeededExpoProfile } from "./expo-seed";
import type { SeedShowroomBrief } from "./showroom-seed-briefs";
import type { ShowroomColorPalette } from "./showroom-design-systems";

type StyleKey =
  | "circuit"
  | "utility"
  | "precision"
  | "botanical"
  | "ritual"
  | "ingredient"
  | "provenance"
  | "pantry"
  | "workshop"
  | "material"
  | "room"
  | "atelier";

type NeutralKey = "cool" | "paper" | "fresh";

type RawOffering = readonly [
  name: string,
  category: string,
  kind: DenseDemoOfferingKind,
  description: string,
];

type RawClient = {
  name: string;
  tagline: string;
  customer: string;
  customerRequest: string;
  paletteRequest: string;
  paletteAdvice: string;
  colors: readonly [string, string, string, string];
  neutral: NeutralKey;
  style: StyleKey;
  logoConcept: string;
  visualThesis: string;
  heroTitle: string;
  heroSubtitle: string;
  process: readonly [string, string, string];
  offerings: readonly [RawOffering, RawOffering, RawOffering, RawOffering];
};

export type ScaleDemoBusiness = {
  handle: string;
  name: string;
  tagline: string;
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  industryKey: string;
  logoPath: string;
  heroPath: string;
  boothPath: string;
  profile: SeededExpoProfile;
  brief: SeedShowroomBrief;
  creative: {
    customer: string;
    customerRequest: string;
    paletteRequest: string;
    paletteAdvice: string;
    logoConcept: string;
    visualThesis: string;
    foundationReason: string;
  };
  offerings: Array<{
    name: string;
    category: string;
    description: string;
    kind: DenseDemoOfferingKind;
    imagePath: string;
  }>;
};

const locations: readonly SeededExpoProfile[] = [
  { industryKeys: [], city: "Addis Ababa", zone: "Addis Ababa", region: "Addis Ababa", latitude: 9.018, longitude: 38.748 },
  { industryKeys: [], city: "Addis Ababa", zone: "Addis Ababa", region: "Addis Ababa", latitude: 8.982, longitude: 38.781 },
  { industryKeys: [], city: "Adama", zone: "East Shewa", region: "Oromia", latitude: 8.545, longitude: 39.272 },
  { industryKeys: [], city: "Bishoftu", zone: "East Shewa", region: "Oromia", latitude: 8.748, longitude: 38.982 },
  { industryKeys: [], city: "Bahir Dar", zone: "Bahir Dar", region: "Amhara", latitude: 11.579, longitude: 37.367 },
  { industryKeys: [], city: "Hawassa", zone: "Sidama", region: "Sidama", latitude: 7.058, longitude: 38.477 },
  { industryKeys: [], city: "Dire Dawa", zone: "Dire Dawa urban", region: "Dire Dawa", latitude: 9.594, longitude: 41.856 },
  { industryKeys: [], city: "Jimma", zone: "Jimma", region: "Oromia", latitude: 7.681, longitude: 36.839 },
  { industryKeys: [], city: "Hosaena", zone: "Hadiya", region: "Central Ethiopia", latitude: 7.553, longitude: 37.854 },
  { industryKeys: [], city: "Robe", zone: "Bale", region: "Oromia", latitude: 7.118, longitude: 40.003 },
  { industryKeys: [], city: "Gondar", zone: "Central Gondar", region: "Amhara", latitude: 12.607, longitude: 37.463 },
  { industryKeys: [], city: "Arba Minch", zone: "Gamo", region: "South Ethiopia", latitude: 6.036, longitude: 37.55 },
];

const locationPlans: Record<string, readonly number[]> = {
  electronics: [0, 0, 0, 2, 2, 2, 6, 7],
  "beauty-wellness": [0, 0, 0, 9, 9, 9, 5, 7],
  "food-farming": [7, 7, 7, 4, 4, 4, 11, 9],
  "machinery-tools": [2, 2, 2, 6, 6, 6, 0, 8],
  "home-living": [5, 5, 5, 8, 8, 8, 0, 11],
  "fashion-textiles": [0, 0, 0, 5, 5, 5, 4, 10],
};

const styleProfiles: Record<StyleKey, Omit<SeedShowroomBrief["profile"], "customPalette">> = {
  circuit: { tokenPack: "chrome-future", motion: "expressive", decoration: "clean", header: "header.technical-marquee@1", hero: "hero.technology-cinematic@1", story: "content.exploded-feature@1", highlights: "content.production-metrics@1", catalog: "catalog.minimal-list@1", cta: "call-to-action.technical-brief@1", footer: "footer.technical-directory@1", ctaVariant: "technical-brief", heroMediaIntegration: "surface_blend", storyMediaIntegration: "natural", productDetailPattern: "technical" },
  utility: { tokenPack: "ocean-trade", motion: "balanced", decoration: "clean", header: "header.compact-utility@1", hero: "hero.split-story@1", story: "content.origin-story@1", highlights: "content.process-steps@1", catalog: "catalog.minimal-list@1", cta: "call-to-action.inquiry@1", footer: "footer.compact@1", ctaVariant: "technical-brief", heroMediaIntegration: "split_bleed", storyMediaIntegration: "natural", productDetailPattern: "compact" },
  precision: { tokenPack: "technology-mono", motion: "quiet", decoration: "clean", header: "header.catalog-command@1", hero: "hero.product-spotlight@1", story: "content.editorial-quote@1", highlights: "content.production-metrics@1", catalog: "catalog.feature-tiles@1", cta: "call-to-action.technical-brief@1", footer: "footer.contact-panel@1", ctaVariant: "technical-brief", heroMediaIntegration: "product_stage", storyMediaIntegration: "natural", productDetailPattern: "technical" },
  botanical: { tokenPack: "forest-botanical", motion: "quiet", decoration: "subtle", header: "header.producer-badge@1", hero: "hero.provenance@1", story: "content.founder-note@1", highlights: "content.process-steps@1", catalog: "catalog.horizontal-shelf@1", cta: "call-to-action.sample-question@1", footer: "footer.catalog-directory@1", ctaVariant: "magazine-close", heroMediaIntegration: "edge_fade", storyMediaIntegration: "natural", productDetailPattern: "compact" },
  ritual: { tokenPack: "cosmetic-laboratory", motion: "expressive", decoration: "signature", header: "header.floating-capsule@1", hero: "hero.beauty-orbit@1", story: "content.founder-note@1", highlights: "content.ritual-steps@1", catalog: "catalog.beauty-swatch@1", cta: "call-to-action.magazine-close@1", footer: "footer.magazine-masthead@1", ctaVariant: "magazine-close", heroMediaIntegration: "product_stage", storyMediaIntegration: "natural", productDetailPattern: "product_stage" },
  ingredient: { tokenPack: "mineral-spa", motion: "balanced", decoration: "subtle", header: "header.editorial-wordmark@1", hero: "hero.ingredient-monograph@1", story: "content.material-focus@1", highlights: "content.ritual-steps@1", catalog: "catalog.editorial-grid@1", cta: "call-to-action.consultation@1", footer: "footer.editorial@1", ctaVariant: "magazine-close", heroMediaIntegration: "surface_blend", storyMediaIntegration: "natural", productDetailPattern: "editorial" },
  provenance: { tokenPack: "harvest-earth", motion: "quiet", decoration: "subtle", header: "header.producer-badge@1", hero: "hero.provenance@1", story: "content.origin-story@1", highlights: "content.process-steps@1", catalog: "catalog.horizontal-shelf@1", cta: "call-to-action.wholesale@1", footer: "footer.catalog-directory@1", ctaVariant: "magazine-close", heroMediaIntegration: "edge_fade", storyMediaIntegration: "natural", productDetailPattern: "compact" },
  pantry: { tokenPack: "honey-amber", motion: "balanced", decoration: "signature", header: "header.transparent-overlay@1", hero: "hero.ingredient-monograph@1", story: "content.lookbook-chapter@1", highlights: "content.process-steps@1", catalog: "catalog.collection-led@1", cta: "call-to-action.wholesale@1", footer: "footer.magazine-masthead@1", ctaVariant: "magazine-close", heroMediaIntegration: "surface_blend", storyMediaIntegration: "natural", productDetailPattern: "editorial" },
  workshop: { tokenPack: "industrial-steel", motion: "quiet", decoration: "clean", header: "header.compact-utility@1", hero: "hero.industrial-spec@1", story: "content.origin-story@1", highlights: "content.production-metrics@1", catalog: "catalog.minimal-list@1", cta: "call-to-action.technical-brief@1", footer: "footer.technical-directory@1", ctaVariant: "technical-brief", heroMediaIntegration: "split_bleed", storyMediaIntegration: "natural", productDetailPattern: "technical" },
  material: { tokenPack: "artisan-clay", motion: "balanced", decoration: "subtle", header: "header.editorial-wordmark@1", hero: "hero.material-detail@1", story: "content.material-focus@1", highlights: "content.process-steps@1", catalog: "catalog.editorial-grid@1", cta: "call-to-action.consultation@1", footer: "footer.editorial@1", ctaVariant: "magazine-close", heroMediaIntegration: "editorial_overlap", storyMediaIntegration: "natural", productDetailPattern: "editorial" },
  room: { tokenPack: "paper-gallery", motion: "balanced", decoration: "signature", header: "header.catalog-command@1", hero: "hero.room-scene@1", story: "content.lookbook-chapter@1", highlights: "content.process-steps@1", catalog: "catalog.room-set@1", cta: "call-to-action.consultation@1", footer: "footer.contact-panel@1", ctaVariant: "magazine-close", heroMediaIntegration: "surface_blend", storyMediaIntegration: "natural", productDetailPattern: "product_stage" },
  atelier: { tokenPack: "silk-atelier", motion: "expressive", decoration: "signature", header: "header.editorial-wordmark@1", hero: "hero.textile-swatch@1", story: "content.swatch-story@1", highlights: "content.process-steps@1", catalog: "catalog.textile-stack@1", cta: "call-to-action.magazine-close@1", footer: "footer.magazine-masthead@1", ctaVariant: "magazine-close", heroMediaIntegration: "editorial_overlap", storyMediaIntegration: "natural", productDetailPattern: "editorial" },
};

const neutralRoles: Record<NeutralKey, Pick<ShowroomColorPalette, "canvas" | "surface" | "layer" | "text" | "textMuted" | "inverse" | "onInverse" | "border">> = {
  cool: { canvas: "#ffffff", surface: "#f3f6f8", layer: "#e4eaf0", text: "#17212b", textMuted: "#596572", inverse: "#111820", onInverse: "#ffffff", border: "#c7d0d8" },
  paper: { canvas: "#ffffff", surface: "#f6f5f2", layer: "#e9e6df", text: "#211f1c", textMuted: "#67625b", inverse: "#171614", onInverse: "#ffffff", border: "#d2cec5" },
  fresh: { canvas: "#ffffff", surface: "#f2f6f4", layer: "#e1eae5", text: "#17241e", textMuted: "#5b6961", inverse: "#111a16", onInverse: "#ffffff", border: "#c8d3cd" },
};

function palette(raw: RawClient): ShowroomColorPalette {
  const [primary, primarySoft, secondary, secondarySoft] = raw.colors;
  return {
    ...neutralRoles[raw.neutral],
    primary,
    primarySoft,
    secondary,
    secondarySoft,
    onSecondary: "#ffffff",
    strong: secondary,
    onStrong: "#ffffff",
  };
}

const clientGroups: Array<{ industryKey: string; clients: readonly RawClient[] }> = [
  { industryKey: "electronics", clients: [
    { name: "Aster Device Workshop", tagline: "Small controls made understandable.", customer: "repair shops and small production teams", customerRequest: "Show that we build useful controls as well as repair electronics; keep the site technical without making it cold.", paletteRequest: "bright blue, cyan, and black", paletteAdvice: "Cyan on white was too weak for controls, so cyan stays decorative while deep ink-blue carries actions and contrast.", colors: ["#087ea4", "#d4edf4", "#17427a", "#dbe6f5"], neutral: "cool", style: "circuit", logoConcept: "an A formed by two circuit traces", visualThesis: "A crisp bench diagram energized by one bright signal color.", heroTitle: "Controls built for the equipment already at work.", heroSubtitle: "Inspect compact builds, diagnostics, and labeled assemblies before sending the requirement.", process: ["Trace the requirement", "Build and bench-test", "Label and document"], offerings: [["Motor Timer Control", "Controls", "made_to_order", "A protected timer assembly configured for a motor duty cycle."], ["Rechargeable Inspection Light", "Devices", "standard_product", "A compact work light with a replaceable battery pack."], ["Appliance Board Diagnostic", "Repair", "made_to_order", "Bench diagnosis for eligible appliance control boards."], ["Labeled Control Harness", "Assemblies", "manufacturing_capability", "A short-run harness built to connector and length requirements."]] },
    { name: "Lume Solar Repair", tagline: "Keep practical solar gear working longer.", customer: "households, kiosks, and field operators", customerRequest: "Make repair feel trustworthy and show complete small solar kits without looking like a large utility company.", paletteRequest: "yellow everywhere with dark gray", paletteAdvice: "A full yellow interface would reduce readability; warm yellow becomes the energy cue against white, with deep teal for dependable actions.", colors: ["#c88700", "#f7e5b8", "#145c63", "#d6eaeb"], neutral: "cool", style: "utility", logoConcept: "a half-sun rising through a repair ring", visualThesis: "Daylight utility with clear before-and-after product evidence.", heroTitle: "Repair the kit. Restore the light.", heroSubtitle: "Compare service options, replacement parts, and compact solar packages in one direct workshop catalog.", process: ["Check the load and fault", "Repair or configure", "Test under working load"], offerings: [["Lantern Battery Rebuild", "Repair", "made_to_order", "A cell and protection-board rebuild for compatible lanterns."], ["Charge Controller Repair", "Repair", "made_to_order", "Diagnosis and component repair for eligible small controllers."], ["Two-Room Solar Kit", "Solar Kits", "standard_product", "A compact lighting package with labeled connections."], ["Weatherproof DC Cable Set", "Connections", "manufacturing_capability", "Cut, terminated, and tested cable sets for small installations."]] },
    { name: "Tana Radio Works", tagline: "Audio equipment returned to clear service.", customer: "homes, worship spaces, and neighborhood venues", customerRequest: "Use some vintage character, but keep the product and repair information modern and easy to scan.", paletteRequest: "brown, orange, and cream", paletteAdvice: "The requested colors felt nostalgic but muddy together; copper is retained as a detail while navy and clean gray sharpen the interface.", colors: ["#b6552d", "#f1d9ce", "#263f70", "#dce4f2"], neutral: "paper", style: "precision", logoConcept: "concentric radio waves inside a T", visualThesis: "A precise listening-room mood with restrained analog detail.", heroTitle: "Old signal, clear sound, useful life again.", heroSubtitle: "Browse restorations, audio repairs, antennas, and made-to-length connection work.", process: ["Listen and diagnose", "Repair the signal path", "Test every input"], offerings: [["Table Radio Restoration", "Restoration", "made_to_order", "Electrical and cabinet restoration for eligible table radios."], ["PA Amplifier Repair", "Repair", "made_to_order", "Bench service for compatible public-address amplifiers."], ["Outdoor FM Antenna Kit", "Reception", "standard_product", "A practical antenna and lead set for stronger local reception."], ["Custom Audio Cable Loom", "Connections", "manufacturing_capability", "Labeled audio looms built to connector and routing needs."]] },
    { name: "Shewa Cable Studio", tagline: "Every connection cut, marked, and checked.", customer: "installers and equipment builders", customerRequest: "Make it obvious that customers can order repeated cable assemblies from a small specialist.", paletteRequest: "red and black only", paletteAdvice: "Pure red and black felt aggressive and made states hard to distinguish; brick red remains the mark while marine blue adds a second functional signal.", colors: ["#b64332", "#f2d9d4", "#075a78", "#d6e8ee"], neutral: "cool", style: "circuit", logoConcept: "two cable ends meeting to form an S", visualThesis: "Orderly routing lines, generous white space, and labeled product photography.", heroTitle: "Cable assemblies that arrive ready to route.", heroSubtitle: "Choose a common build or send connector, length, label, and repeat-quantity requirements.", process: ["Confirm pinout and route", "Cut, terminate, and label", "Continuity-test the run"], offerings: [["Solar Drop Cable", "Power Cables", "manufacturing_capability", "Weather-ready cable assemblies for compact solar installations."], ["Pump Control Harness", "Harnesses", "manufacturing_capability", "A labeled harness built around an approved pump-control diagram."], ["Appliance Lead Assembly", "Power Cables", "manufacturing_capability", "Repeat appliance leads with strain relief and tested termination."], ["Numbered Cable Label Set", "Labels", "standard_product", "Durable sequential labels prepared for installation teams."]] },
    { name: "Desta Appliance Repair", tagline: "Straight answers for equipment worth fixing.", customer: "households and small food businesses", customerRequest: "Lead with repair confidence and make it easy to understand which appliances we accept.", paletteRequest: "green because repair is sustainable", paletteAdvice: "Green alone looked generic, so a deep repair-bay blue provides structure and a vivid green is reserved for successful service cues.", colors: ["#218a5a", "#d7ecdf", "#184d70", "#d9e7ef"], neutral: "fresh", style: "utility", logoConcept: "a D shaped like an open tool case", visualThesis: "Friendly service clarity with equipment shown at working scale.", heroTitle: "Diagnose first. Repair what makes sense.", heroSubtitle: "See accepted repair types and describe the model, fault, and urgency before bringing equipment in.", process: ["Record model and fault", "Diagnose before approval", "Repair and load-test"], offerings: [["Refrigerator Control Diagnostic", "Cooling", "made_to_order", "Control and sensor diagnosis for eligible refrigerators."], ["Blender Motor Rewind", "Kitchen Equipment", "made_to_order", "Motor inspection and rewind for compatible commercial blenders."], ["Commercial Cooker Service", "Kitchen Equipment", "made_to_order", "Electrical service for eligible countertop cookers."], ["Replacement Wiring Loom", "Parts", "manufacturing_capability", "A measured replacement loom for supported appliance models."]] },
    { name: "Orbit Meter Workshop", tagline: "Measurement restored with a clear record.", customer: "workshops, landlords, and equipment technicians", customerRequest: "The page should feel accurate and calm, with enough detail for a technician to decide whether to inquire.", paletteRequest: "silver and electric blue", paletteAdvice: "Silver has too little identity on screen; cool neutrals remain while saturated cobalt and dark teal establish hierarchy.", colors: ["#2367c9", "#d9e6f8", "#145c63", "#d6eaeb"], neutral: "cool", style: "precision", logoConcept: "a meter needle orbiting a small O", visualThesis: "Instrument-panel precision without dashboard clutter.", heroTitle: "Meters checked against the work they must measure.", heroSubtitle: "Review calibration, repair, counters, and small sensor-display builds.", process: ["Identify range and use", "Inspect and compare", "Calibrate and record"], offerings: [["Analog Meter Calibration", "Calibration", "made_to_order", "Range and response checking for eligible analog meters."], ["Digital Panel Meter Repair", "Repair", "made_to_order", "Board-level service for compatible digital panel meters."], ["Pump Hour Counter", "Instruments", "standard_product", "A compact counter assembly for maintenance tracking."], ["Sensor Display Assembly", "Assemblies", "manufacturing_capability", "A configured display enclosure for an approved sensor input."]] },
    { name: "Kora Solar Lights", tagline: "Light made for courtyards, stalls, and study.", customer: "families and market sellers", customerRequest: "Make the lights feel warm and approachable, not like technical solar equipment.", paletteRequest: "sunset orange and purple", paletteAdvice: "The two saturated hues competed; warm coral leads the brand while a dark plum anchors text and calls to action.", colors: ["#d45a36", "#f5ddd4", "#5a315f", "#eaddea"], neutral: "paper", style: "ritual", logoConcept: "a lantern glow inside a simple K", visualThesis: "Warm evening light staged against clean, quiet surfaces.", heroTitle: "A dependable pool of light where the day continues.", heroSubtitle: "Explore ready-to-use solar lights and ask about replacement batteries or small multi-light sets.", process: ["Match light to the place", "Charge and runtime test", "Pack with clear setup"], offerings: [["Courtyard Solar Lamp", "Outdoor Lights", "standard_product", "A freestanding light for gates, paths, and courtyards."], ["Market Stall Light Kit", "Work Lights", "standard_product", "A panel, battery, and two-light kit for evening stalls."], ["Portable Study Light", "Portable Lights", "standard_product", "A rechargeable directional light with two brightness levels."], ["Replacement Battery Pack", "Parts", "made_to_order", "A tested replacement pack for supported Kora light models."]] },
    { name: "Nile Sensor Studio", tagline: "Small sensors for everyday operating questions.", customer: "growers, property operators, and small workshops", customerRequest: "Explain what each sensor tells the customer instead of overwhelming them with circuit details.", paletteRequest: "blue and aqua", paletteAdvice: "Similar blues blurred together, so aqua becomes the measurement highlight while a deep violet creates a distinct action layer.", colors: ["#008a9a", "#d2ecef", "#433b83", "#e2e0f2"], neutral: "cool", style: "circuit", logoConcept: "a water line crossing a sensor node", visualThesis: "Visible readings, simple diagrams, and close product detail.", heroTitle: "Know when the tank, room, or pump changes.", heroSubtitle: "Choose a monitoring starting point or describe the signal and alert you need.", process: ["Define the condition", "Configure sensor and display", "Test the alert range"], offerings: [["Water Tank Level Monitor", "Water Sensors", "standard_product", "A simple visual monitor for compatible household tanks."], ["Greenhouse Temperature Node", "Climate Sensors", "standard_product", "A protected temperature display for small growing spaces."], ["Pump Pressure Alert", "Equipment Sensors", "made_to_order", "A configured pressure threshold and local alert assembly."], ["Custom Sensor Interface", "Assemblies", "manufacturing_capability", "A small interface built for an approved low-voltage sensor."]] },
  ] },
  { industryKey: "beauty-wellness", clients: [
    { name: "Aloe Field Care", tagline: "Aloe care with nothing hidden behind the label.", customer: "customers with simple skin-care routines", customerRequest: "Show the aloe source and make ingredients easy to compare without looking medicinal.", paletteRequest: "all pale green", paletteAdvice: "Pale green everywhere lacked contrast; fresh white and deep leaf green frame a restrained aloe accent.", colors: ["#3f8f69", "#d8ecdf", "#215a4c", "#d7e9e4"], neutral: "fresh", style: "botanical", logoConcept: "three aloe leaves forming an A", visualThesis: "Fresh field provenance paired with clean ingredient notes.", heroTitle: "Aloe-led care from leaf to finished bottle.", heroSubtitle: "Compare simple formulas, textures, and intended use before asking the maker.", process: ["Prepare the aloe base", "Blend the small batch", "Fill and label"], offerings: [["Cooling Aloe Gel", "Skin Care", "standard_product", "A light aloe gel for everyday external use."], ["Aloe Body Lotion", "Body Care", "standard_product", "A fluid moisturizer with aloe and a clean finish."], ["Aloe Scalp Mist", "Hair Care", "standard_product", "A fine mist designed for light scalp hydration."], ["Hospitality Aloe Minis", "Custom Batches", "made_to_order", "A small labeled run for guest rooms and welcome sets."]] },
    { name: "Muna Botanical Studio", tagline: "Botanical blends designed as quiet daily rituals.", customer: "gift buyers and ingredient-conscious adults", customerRequest: "Make the page elegant but not pink, and show the oils as crafted objects.", paletteRequest: "dusty rose and beige", paletteAdvice: "Rose and beige risked the familiar one-note beauty look; muted berry is paired with ink blue and white gallery space.", colors: ["#a63f64", "#f1d8e2", "#2f4677", "#dde4f1"], neutral: "paper", style: "ritual", logoConcept: "a crescent holding one botanical stem", visualThesis: "Editorial still life with one botanical gesture and jewel-toned anchors.", heroTitle: "Plant oils composed for slower care.", heroSubtitle: "Browse face, body, and hair rituals with clear texture and use notes.", process: ["Choose the plant profile", "Blend by measured formula", "Rest, fill, and finish"], offerings: [["Evening Face Oil", "Face Care", "standard_product", "A light facial oil for a simple evening routine."], ["Botanical Body Serum", "Body Care", "standard_product", "A dry-touch oil blend for post-bath care."], ["Nourishing Hair Drops", "Hair Care", "standard_product", "A concentrated oil for ends and protective styles."], ["Ritual Gift Quartet", "Gift Sets", "made_to_order", "Four small oils coordinated for gifting."]] },
    { name: "Liya Soap Kitchen", tagline: "Everyday bars with a visible batch story.", customer: "families, gift shops, and guesthouses", customerRequest: "Keep it cheerful and handmade without using rustic kraft-paper styling.", paletteRequest: "orange, cream, and brown", paletteAdvice: "Warm neutrals made the bars disappear; tangerine remains playful while deep blue and white sharpen the shelf.", colors: ["#cf5b24", "#f5ded2", "#224f7a", "#d9e6f1"], neutral: "cool", style: "ingredient", logoConcept: "a soap bar with one clean rising bubble", visualThesis: "Bright batch color on a disciplined, clean product shelf.", heroTitle: "A good bar should explain what is inside.", heroSubtitle: "Compare everyday soaps, gift formats, and small hospitality runs.", process: ["Measure oils and lye", "Cut and cure", "Inspect and wrap"], offerings: [["Oat Everyday Bar", "Daily Soap", "standard_product", "A mild unscented-style bar with finely milled oat."], ["Citrus Kitchen Bar", "Kitchen Soap", "standard_product", "A firm cleansing bar for hands after kitchen work."], ["Coffee Scrub Bar", "Body Soap", "standard_product", "A textured body bar made in a limited batch."], ["Wrapped Guest Soap Run", "Wholesale", "made_to_order", "Small wrapped bars prepared for hospitality quantities."]] },
    { name: "Biftu Natural Oils", tagline: "Pressed oils with a clear source and purpose.", customer: "hair-care customers and small retailers", customerRequest: "Lead with the oil quality and let wholesale buyers understand pack options quickly.", paletteRequest: "gold and dark green", paletteAdvice: "The classic pair is retained but separated by bright neutral surfaces so it reads as modern rather than ceremonial.", colors: ["#a97000", "#f3e2b8", "#1f5a46", "#d8e8e1"], neutral: "fresh", style: "ingredient", logoConcept: "a single oil drop containing a seed", visualThesis: "Monograph-like ingredient photography with confident pack information.", heroTitle: "One pressed ingredient, clearly presented.", heroSubtitle: "Review use, texture, bottle format, and small retail supply options.", process: ["Sort and prepare seed", "Press and settle", "Filter, fill, and code"], offerings: [["Black Seed Oil", "Pressed Oils", "standard_product", "A bottled cold-pressed oil with batch coding."], ["Sesame Body Oil", "Body Care", "standard_product", "A simple sesame oil prepared for body-care routines."], ["Hair and Scalp Oil", "Hair Care", "standard_product", "A blended oil for scalp massage and protective styles."], ["Retail Refill Batch", "Wholesale", "production_supply", "A recurring bottle or refill supply discussed by batch."]] },
    { name: "Hana Herbal Works", tagline: "Highland herbs prepared for practical home rituals.", customer: "adults seeking simple botanical preparations", customerRequest: "Use the feeling of gathered herbs but keep the page factual and easy to read.", paletteRequest: "forest green and tan", paletteAdvice: "Tan and green felt too earthy together; ochre becomes a small botanical cue and mineral blue adds clean section contrast.", colors: ["#3b7850", "#dbeadf", "#2c5682", "#dce6f1"], neutral: "fresh", style: "botanical", logoConcept: "an H built from two leaves and a stem", visualThesis: "Pressed-botanical clarity rather than a rustic apothecary set.", heroTitle: "Herbal preparations organized by how they are used.", heroSubtitle: "See ingredients, format, and preparation notes before starting a question.", process: ["Sort the botanicals", "Dry or infuse", "Pack with use notes"], offerings: [["Highland Herb Infusion", "Dried Herbs", "standard_product", "A clearly labeled dried botanical blend."], ["Warming Massage Oil", "Infused Oils", "standard_product", "A botanical infusion prepared in a light carrier oil."], ["Steam Bowl Blend", "Home Rituals", "standard_product", "A measured aromatic blend with simple preparation guidance."], ["Guest Wellness Set", "Custom Sets", "made_to_order", "A coordinated small-format set for hospitality use."]] },
    { name: "Sena Body Care", tagline: "Body care that feels bright, useful, and uncomplicated.", customer: "young adults and practical gift buyers", customerRequest: "Make it energetic and modern, with products that look affordable but considered.", paletteRequest: "hot pink and purple", paletteAdvice: "Two loud hues competed with product reading; vivid berry leads, balanced by deep teal and clean gray.", colors: ["#c52f6a", "#f4d6e2", "#17616a", "#d5e9eb"], neutral: "cool", style: "ritual", logoConcept: "an S made from two lotion swipes", visualThesis: "Confident color blocks around clean, tactile product close-ups.", heroTitle: "Simple body care with a little more energy.", heroSubtitle: "Build a daily set from washes, butters, scrubs, and compact gifts.", process: ["Choose texture and scent", "Mix the short batch", "Fill, seal, and pair"], offerings: [["Daily Body Wash", "Cleansing", "standard_product", "A straightforward liquid wash in a practical pump bottle."], ["Whipped Body Butter", "Moisture", "standard_product", "A rich body butter with a soft whipped texture."], ["Sugar Polish", "Exfoliation", "standard_product", "A rinse-off body polish made in small batches."], ["Bright Body Pair", "Gift Sets", "made_to_order", "A coordinated wash and butter pair for gifting."]] },
    { name: "Meriem Hair Care", tagline: "Care for coils, braids, and protective styles.", customer: "customers maintaining textured hair and braids", customerRequest: "Put the routine first and make each product role obvious on a phone.", paletteRequest: "black and gold luxury", paletteAdvice: "A full black-and-gold treatment felt heavy; black remains an inverse anchor while cobalt and warm gold make the routine easier to navigate.", colors: ["#b77a00", "#f3e3bb", "#3155a5", "#dce4f4"], neutral: "paper", style: "ritual", logoConcept: "a flowing M echoing a braided strand", visualThesis: "A clear step-by-step hair ritual with sculptural containers.", heroTitle: "A focused routine for hair that stays in motion.", heroSubtitle: "Compare cleanse, moisture, scalp, and finish products by the role they play.", process: ["Start with the routine", "Blend for texture", "Fill and use-test"], offerings: [["Gentle Scalp Cleanser", "Cleanse", "standard_product", "A targeted cleanser for scalp and protective-style care."], ["Leave-In Moisture Milk", "Moisture", "standard_product", "A lightweight leave-in for coils and braids."], ["Braid and Scalp Drops", "Scalp Care", "standard_product", "A fine-tip oil blend for parted styles."], ["Protective Style Set", "Routine Sets", "made_to_order", "A coordinated cleanser, milk, and scalp oil set."]] },
    { name: "Zema Plant Balms", tagline: "Compact plant balms for hands, lips, and travel.", customer: "market shoppers and practical gift buyers", customerRequest: "Make the tins feel collectible and natural without covering the site in leaves.", paletteRequest: "sage, beige, and terracotta", paletteAdvice: "The three muted colors blended together; sage stays soft while terracotta sharpens labels and a deep marine tone anchors actions.", colors: ["#b44d37", "#f0dad3", "#21556f", "#d9e6ed"], neutral: "paper", style: "ingredient", logoConcept: "a round tin with a tiny sprouting Z", visualThesis: "Small objects enlarged through editorial scale and clean circular rhythm.", heroTitle: "Useful plant care that fits in the palm.", heroSubtitle: "Browse compact balms by purpose, texture, and gift format.", process: ["Infuse the oil", "Melt and blend", "Pour, cool, and label"], offerings: [["Working Hand Balm", "Hand Care", "standard_product", "A firm balm for hands exposed to frequent washing and work."], ["Soft Lip Balm", "Lip Care", "standard_product", "A compact everyday balm with a smooth finish."], ["Heel and Elbow Balm", "Targeted Care", "standard_product", "A richer balm for dry, high-friction areas."], ["Pocket Balm Trio", "Gift Sets", "made_to_order", "Three small tins prepared as a practical gift set."]] },
  ] },
  { industryKey: "food-farming", clients: [
    { name: "Bora Highland Farm", tagline: "Highland harvests packed around the week.", customer: "households and small kitchens", customerRequest: "Show what is fresh now and make recurring crate inquiries feel simple.", paletteRequest: "green and soil brown", paletteAdvice: "Brown and green made the page too earthy; field green remains while clear blue adds freshness and stronger section distinction.", colors: ["#3d7b42", "#dcebd9", "#285f85", "#dbe8f0"], neutral: "fresh", style: "provenance", logoConcept: "two terraced field lines forming a B", visualThesis: "Open-air freshness with harvest detail and clear weekly rhythm.", heroTitle: "A highland harvest organized for real kitchens.", heroSubtitle: "See the current greens, roots, herbs, and mixed crate before asking about the next supply day.", process: ["Walk the current field", "Harvest and sort", "Pack for the route"], offerings: [["Highland Greens Crate", "Greens", "production_supply", "A rotating crate of current leafy harvests."], ["Root Vegetable Mix", "Roots", "production_supply", "A practical mix of cleaned seasonal root vegetables."], ["Kitchen Herb Bundle", "Herbs", "standard_product", "A bundled selection of current aromatic herbs."], ["Weekly Family Harvest", "Recurring Crates", "production_supply", "A recurring mixed crate discussed by household size."]] },
    { name: "Laga Grain Mill", tagline: "Local grain milled to the texture the kitchen needs.", customer: "families, cafes, and small bakeries", customerRequest: "Let buyers compare grain and milling style quickly, with a clean trustworthy mill feel.", paletteRequest: "wheat gold and brown", paletteAdvice: "Gold and brown repeated the old mill stereotype; grain gold is paired with deep ocean blue and bright neutral layers.", colors: ["#a96f08", "#f2e2bc", "#1d5c78", "#d7e7ee"], neutral: "paper", style: "pantry", logoConcept: "a grain kernel inside a simple mill wheel", visualThesis: "Precise package and grain detail with a strong modern trade color.", heroTitle: "Choose the grain. Choose the grind.", heroSubtitle: "Compare household packs, bakery formats, and recurring milling supply.", process: ["Inspect and clean grain", "Set the milling texture", "Pack and batch-mark"], offerings: [["Ivory Teff Flour", "Teff", "production_supply", "Fine-milled ivory teff in household and kitchen formats."], ["Brown Teff Flour", "Teff", "production_supply", "Whole-grain brown teff with a fuller character."], ["Roasted Barley Flour", "Barley", "standard_product", "Roasted barley milled for traditional drinks and baking."], ["Bakery Grain Blend", "Blends", "made_to_order", "A repeat blend discussed around recipe and pack size."]] },
    { name: "Mulu Family Farm", tagline: "A family field with a clear seasonal table.", customer: "nearby households and cafes", customerRequest: "Make the farm personal and warm, but keep products and availability easier to scan than social media.", paletteRequest: "soft green and cream", paletteAdvice: "The two pale colors lacked hierarchy; a richer leaf green and berry-red detail create useful contrast on white.", colors: ["#3c7d55", "#d9eadf", "#9c3345", "#efdadd"], neutral: "fresh", style: "provenance", logoConcept: "four leaves gathered into an M", visualThesis: "Family-scale warmth expressed through harvest portraits, not decorative rustic texture.", heroTitle: "What the family field is ready to share.", heroSubtitle: "Browse seasonal vegetables, eggs, herbs, and a rotating mixed basket.", process: ["Plan the weekly pick", "Gather and grade", "Pack by customer need"], offerings: [["Seasonal Vegetable Basket", "Vegetables", "production_supply", "A mixed basket based on the week's field harvest."], ["Farm Egg Tray", "Eggs", "production_supply", "A tray format confirmed against the current laying cycle."], ["Fresh Herb Bunches", "Herbs", "standard_product", "Current kitchen herbs bundled after harvest."], ["Cafe Breakfast Supply", "Recurring Supply", "production_supply", "A recurring egg, herb, and vegetable inquiry for small cafes."]] },
    { name: "Kaffa Spice Kitchen", tagline: "Spice blends built from aroma, roast, and balance.", customer: "home cooks, restaurants, and gift buyers", customerRequest: "Make the spices feel vivid and premium without using a dark luxury theme.", paletteRequest: "red, orange, and brown", paletteAdvice: "Three adjacent warm colors made every section compete; paprika red leads, with deep teal cooling and organizing the page.", colors: ["#b43d2c", "#f1d8d2", "#145c63", "#d6eaeb"], neutral: "paper", style: "pantry", logoConcept: "a K cut through a circular spice bowl", visualThesis: "Bright spice texture isolated on crisp paper-white planes.", heroTitle: "The aroma starts before the lid is opened.", heroSubtitle: "Compare house blends, single spices, and kitchen-size packs by flavor direction.", process: ["Source and sort", "Roast and grind", "Blend, taste, and pack"], offerings: [["House Berbere Blend", "Blends", "standard_product", "A balanced red spice blend in household jars."], ["Mild Shiro Seasoning", "Blends", "standard_product", "A gentle aromatic seasoning for shiro preparation."], ["Roasted Korerima", "Single Spices", "standard_product", "Roasted and ground korerima packed in a small batch."], ["Restaurant Spice Pack", "Kitchen Supply", "production_supply", "Larger blend formats discussed for repeat kitchens."]] },
    { name: "Sofi Orchard", tagline: "Fruit picked for eating, juicing, and preserving.", customer: "families, juice makers, and cafes", customerRequest: "Make seasonality obvious and let buyers ask about crates without implying permanent stock.", paletteRequest: "orange and green", paletteAdvice: "The natural pair works when separated: citrus orange is a product cue, while deep green carries navigation and inquiry actions.", colors: ["#d06418", "#f5dfc8", "#286044", "#d9e8df"], neutral: "fresh", style: "provenance", logoConcept: "a fruit branch forming a compact S", visualThesis: "Sunlit fruit close-ups with a clean seasonal availability rhythm.", heroTitle: "Orchard fruit in the season it belongs to.", heroSubtitle: "See current fruit formats and discuss household bags, juice crates, or preserving quantities.", process: ["Check ripeness", "Pick and grade", "Pack for use"], offerings: [["Seasonal Citrus Bag", "Fresh Fruit", "production_supply", "A household bag selected from the current citrus harvest."], ["Juicing Fruit Crate", "Kitchen Supply", "production_supply", "A practical crate of ripe fruit for juice preparation."], ["Orchard Tasting Box", "Mixed Fruit", "standard_product", "A smaller mixed box when several fruits overlap in season."], ["Preserving Fruit Batch", "Bulk Fruit", "production_supply", "A larger ripe-fruit inquiry for jam and preserve making."]] },
    { name: "Wabi Flour Mill", tagline: "Everyday flour with the mill settings made clear.", customer: "households and neighborhood bakeries", customerRequest: "Show consistency and useful pack choices; avoid old-fashioned sack graphics.", paletteRequest: "cream and maroon", paletteAdvice: "Cream surfaces dulled the product photography; white and cool gray keep flour clean while maroon is balanced by slate blue.", colors: ["#8f3348", "#eed9df", "#315a75", "#dae5eb"], neutral: "cool", style: "precision", logoConcept: "a W built from four measured grain lines", visualThesis: "Measured, clean milling expressed through texture and pack geometry.", heroTitle: "A consistent grind for the way you bake.", heroSubtitle: "Compare grain, texture, and pack format for home or repeat kitchen use.", process: ["Clean and grade grain", "Set and monitor grind", "Check texture and seal"], offerings: [["White Wheat Flour", "Wheat", "production_supply", "Fine wheat flour packed for household baking."], ["Whole Wheat Flour", "Wheat", "production_supply", "A fuller whole-grain flour with clear pack dating."], ["Teff-Wheat Baking Blend", "Blends", "standard_product", "A balanced blend for flatbreads and test baking."], ["Bakery Repeat Supply", "Trade Supply", "production_supply", "A recurring flour inquiry by blend and pack format."]] },
    { name: "Rift Seed Growers", tagline: "Seed lots presented for the next planting decision.", customer: "small growers and community nurseries", customerRequest: "The site should feel credible and organized, with crop type and lot notes visible early.", paletteRequest: "dark green only", paletteAdvice: "A single dark green made categories merge; leaf green marks growth while cobalt separates records and actions.", colors: ["#2f774d", "#d8eadf", "#2853a0", "#dbe3f3"], neutral: "fresh", style: "precision", logoConcept: "a seed split by a precise horizon line", visualThesis: "Field identity organized with the discipline of a lot record.", heroTitle: "Start the season with a clearer seed inquiry.", heroSubtitle: "Browse current vegetable, herb, and nursery lots, then confirm suitability and supply window.", process: ["Select and clean seed", "Test and record the lot", "Pack for planting"], offerings: [["Tomato Grower Seed", "Vegetable Seed", "production_supply", "A current tomato seed lot for small growing plans."], ["Leafy Green Seed Mix", "Vegetable Seed", "production_supply", "A practical mixed lot for staggered leafy planting."], ["Kitchen Herb Seed Set", "Herb Seed", "standard_product", "Several common herb seeds in a compact starter set."], ["Nursery Seasonal Lot", "Nursery Supply", "production_supply", "A larger seed inquiry coordinated with a nursery plan."]] },
    { name: "Tena Food Kitchen", tagline: "Prepared foods made in short, clearly dated batches.", customer: "busy households and small offices", customerRequest: "Make ordering interest easy without pretending we are a delivery app or showing permanent stock.", paletteRequest: "red and yellow", paletteAdvice: "The fast-food combination was too loud; tomato red remains appetizing while deep blue and white create a calmer kitchen identity.", colors: ["#b83d33", "#f1d9d5", "#274f7c", "#dbe5f1"], neutral: "paper", style: "pantry", logoConcept: "a covered serving bowl with a small T handle", visualThesis: "Fresh batch photography with simple date-and-format cues.", heroTitle: "A short batch, prepared for the week ahead.", heroSubtitle: "Explore ready foods, pantry jars, and group formats, then ask about the next preparation day.", process: ["Plan the short batch", "Cook and portion", "Date, cool, and pack"], offerings: [["Vegetable Lunch Tray", "Prepared Meals", "standard_product", "A rotating vegetable-led meal prepared in a short batch."], ["Spiced Lentil Jar", "Pantry", "standard_product", "A ready lentil base packed for convenient home use."], ["Family Injera Pack", "Staples", "production_supply", "A family-size pack confirmed for the next preparation day."], ["Small Office Lunch Set", "Group Orders", "made_to_order", "A coordinated meal inquiry for a small team."]] },
  ] },
  { industryKey: "machinery-tools", clients: [
    { name: "Shewa Tool Workshop", tagline: "Serviceable hand tools from a working bench.", customer: "craft workers, farms, and repair shops", customerRequest: "Show durability and repairability, not a giant industrial factory.", paletteRequest: "black and orange", paletteAdvice: "The safety pair is retained in moderation, with steel blue separating technical information from calls to action.", colors: ["#c84e24", "#f1d5ca", "#174f70", "#d7e4eb"], neutral: "cool", style: "workshop", logoConcept: "an S made by two opposing wrench jaws", visualThesis: "Honest bench photography organized like a clear tool drawer.", heroTitle: "Tools built to work, return, and work again.", heroSubtitle: "Review standard forms, repairable details, and small-run adaptations.", process: ["Confirm use and material", "Form and heat-treat", "Fit, finish, and test"], offerings: [["Forged Digging Hoe", "Farm Tools", "standard_product", "A forged working hoe with a replaceable handle fit."], ["Workshop Pry Bar", "Hand Tools", "standard_product", "A robust pry bar in practical workshop lengths."], ["Sharpening and Rehandle Service", "Repair", "made_to_order", "Edge restoration and handle replacement for eligible tools."], ["Short-Run Tool Pattern", "Custom Tools", "manufacturing_capability", "A repeat tool form developed from an approved sample."]] },
    { name: "Rift Metal Studio", tagline: "Measured metalwork for interiors and small spaces.", customer: "shops, cafes, and homeowners", customerRequest: "Balance precise fabrication with a more design-conscious presentation.", paletteRequest: "charcoal and rust", paletteAdvice: "Charcoal and rust alone felt heavy; rust becomes a crafted accent while mineral blue brings clear, contemporary contrast.", colors: ["#a94b31", "#efd8d0", "#275a86", "#dbe7f1"], neutral: "paper", style: "material", logoConcept: "a folded sheet creating an angular R", visualThesis: "Architectural metal detail softened by generous gallery space.", heroTitle: "Metalwork measured for the room around it.", heroSubtitle: "Browse compact furniture, display frames, and made-to-fit interior pieces.", process: ["Measure the setting", "Cut, fold, and join", "Finish and fit-check"], offerings: [["Slim Display Shelf", "Interior Metalwork", "standard_product", "A narrow powder-coated shelf for retail or home display."], ["Cafe Table Base", "Furniture Parts", "manufacturing_capability", "Repeat table bases prepared to an approved top size."], ["Plant Stand Pair", "Home Objects", "standard_product", "A paired metal stand in a restrained finish range."], ["Made-to-Fit Counter Frame", "Custom Fabrication", "made_to_order", "A measured support frame for a defined counter surface."]] },
    { name: "Abay Machine Works", tagline: "Compact machines designed around the operator.", customer: "small producers and cooperatives", customerRequest: "Lead with capability and operating fit, with technical details that stay readable on phones.", paletteRequest: "industrial blue and gray", paletteAdvice: "Blue-gray was credible but flat; a controlled red signal adds action and safety emphasis without tinting every section.", colors: ["#bf4437", "#f0d8d4", "#204f78", "#d9e5ed"], neutral: "cool", style: "precision", logoConcept: "an A assembled from two machine rails and a drive wheel", visualThesis: "Compact machine portraits paired with concise operating facts.", heroTitle: "A smaller machine can still be properly specified.", heroSubtitle: "Compare processing tools and send capacity, power, material, and space requirements.", process: ["Review duty and input", "Build the guarded assembly", "Run and document the test"], offerings: [["Compact Grain Cleaner", "Processing", "manufacturing_capability", "A small cleaning assembly configured around grain and throughput."], ["Belt Conveyor Module", "Material Handling", "manufacturing_capability", "A modular conveyor section sized for a defined line."], ["Bench Mixing Unit", "Mixing", "made_to_order", "A guarded mixer configured for an approved batch size."], ["Machine Guard Retrofit", "Safety", "made_to_order", "A measured guard package for eligible working equipment."]] },
    { name: "Tana Welding Shop", tagline: "Fabrication work scoped before the first cut.", customer: "local businesses, builders, and property owners", customerRequest: "Make it easy to show examples and ask for custom work without a huge form.", paletteRequest: "flame orange and black", paletteAdvice: "Orange and black were too severe for residential inquiries; orange stays as the weld cue, balanced by navy and clean gray.", colors: ["#d15b24", "#f4ddcf", "#224b72", "#dbe5ee"], neutral: "cool", style: "utility", logoConcept: "a T ending in one restrained welding spark", visualThesis: "Direct project evidence with strong dimensions and minimal decoration.", heroTitle: "Bring the dimension before bringing the job.", heroSubtitle: "Review gates, frames, stands, and repair work, then send the closest requirement.", process: ["Measure and agree scope", "Cut, tack, and verify", "Weld, finish, and inspect"], offerings: [["Shopfront Security Frame", "Frames", "made_to_order", "A measured welded frame for a defined storefront opening."], ["Water Tank Stand", "Utility Fabrication", "made_to_order", "A support stand designed around tank size and site conditions."], ["Mobile Work Stand", "Workshop Equipment", "standard_product", "A compact wheeled stand for bench and repair work."], ["Weld Repair Visit", "Repair", "made_to_order", "A scoped repair for eligible steel fixtures and frames."]] },
    { name: "Bale Equipment Repair", tagline: "Farm and workshop equipment returned to useful service.", customer: "growers, mills, and local workshops", customerRequest: "Show which equipment we handle and emphasize diagnosis before promises.", paletteRequest: "tractor green and yellow", paletteAdvice: "The familiar pair risked looking like another brand; deep green remains, while ochre is restrained and slate blue structures service information.", colors: ["#9b7200", "#efe3bf", "#24566f", "#d9e5eb"], neutral: "fresh", style: "workshop", logoConcept: "a bearing ring crossed by a repair spanner", visualThesis: "Field repair credibility with close mechanical evidence and clean service bands.", heroTitle: "Find the fault before replacing the machine.", heroSubtitle: "See supported repair types and send model, symptom, location, and urgency.", process: ["Record machine and symptom", "Inspect the failed system", "Repair and working-test"], offerings: [["Small Thresher Service", "Farm Equipment", "made_to_order", "Inspection and repair for eligible compact threshers."], ["Pump and Coupling Repair", "Water Equipment", "made_to_order", "Mechanical service for supported pump and coupling assemblies."], ["Bearing Housing Rebuild", "Workshop Repair", "made_to_order", "A measured rebuild for eligible worn bearing housings."], ["Replacement Guard Fabrication", "Safety Parts", "manufacturing_capability", "A new equipment guard built from approved measurements."]] },
    { name: "Dawa Hand Tools", tagline: "Simple tools shaped for grip, balance, and repair.", customer: "construction crews and craft workers", customerRequest: "Make the hand feel as important as the steel and avoid a catalog that looks imported.", paletteRequest: "red and gray", paletteAdvice: "Red remains a confident maker mark while a deep blue-green and white surfaces give the tools room to read.", colors: ["#b6383d", "#efd7da", "#175d62", "#d5e9e8"], neutral: "cool", style: "material", logoConcept: "a palm-sized D cut from a tool silhouette", visualThesis: "Human-scale tool portraits with tactile handles and crisp shadows.", heroTitle: "A useful tool begins where the hand meets it.", heroSubtitle: "Compare common tools, handle options, and repeat workshop quantities.", process: ["Shape the working end", "Fit and balance the handle", "Finish and strike-test"], offerings: [["Mason Point Chisel", "Masonry Tools", "standard_product", "A forged point chisel with a balanced striking length."], ["Carpenter Claw Hammer", "Carpentry Tools", "standard_product", "A practical hammer with a replaceable fitted handle."], ["Brick Jointing Tool", "Masonry Tools", "standard_product", "A compact double-ended tool for consistent mortar joints."], ["Crew Tool Marking Run", "Custom Tools", "manufacturing_capability", "A repeat tool batch with agreed size and ownership marking."]] },
    { name: "Kaffa Mill Workshop", tagline: "Mill parts and repairs made close to the grain.", customer: "small mills and food processors", customerRequest: "Connect the repair work to actual milling needs and make parts inquiries precise.", paletteRequest: "brown and steel gray", paletteAdvice: "Brown weakened the technical feel; copper references grain and wear while dark teal provides a strong service identity.", colors: ["#a64e26", "#efd8cd", "#17584f", "#d7e8e4"], neutral: "cool", style: "workshop", logoConcept: "a millstone ring with one K-shaped keyway", visualThesis: "Mechanical detail grounded by the material the machine processes.", heroTitle: "Keep the mill aligned with the grain it handles.", heroSubtitle: "Review repair, wear-part, guard, and compact handling work.", process: ["Inspect wear and alignment", "Machine or rebuild", "Reassemble and trial-run"], offerings: [["Mill Shaft Rebuild", "Mill Repair", "made_to_order", "Inspection and rebuild for eligible worn mill shafts."], ["Grain Hopper Fabrication", "Mill Parts", "manufacturing_capability", "A measured hopper built for a defined mill inlet."], ["Pulley and Guard Set", "Drive Parts", "manufacturing_capability", "A configured pulley guard assembly for an approved drive."], ["Compact Feed Chute", "Handling", "made_to_order", "A fitted chute for controlled grain movement."]] },
    { name: "Sidama Fabrication", tagline: "Repeatable frames and fixtures for growing businesses.", customer: "shops, producers, and hospitality operators", customerRequest: "Show both standard repeat items and project fabrication in a clean commercial way.", paletteRequest: "navy with gold", paletteAdvice: "Gold is reduced to a warm detail so the page remains practical; navy is paired with a clear green secondary for distinct sections.", colors: ["#b47b0d", "#f1e3bd", "#1f5e53", "#d7e8e4"], neutral: "cool", style: "precision", logoConcept: "three joined frame corners forming an S", visualThesis: "Repeat-production confidence with architectural product staging.", heroTitle: "A fixture worth repeating starts with one clear build.", heroSubtitle: "Browse standard frames or send dimensions for a small production run.", process: ["Approve the first layout", "Fabricate the repeat set", "Inspect dimensions and finish"], offerings: [["Retail Display Frame", "Retail Fixtures", "manufacturing_capability", "A repeatable powder-coated display frame."], ["Stainless Service Trolley", "Hospitality Equipment", "standard_product", "A mobile two-level trolley for service and utility work."], ["Producer Packing Table", "Work Surfaces", "made_to_order", "A cleanable table configured for a small packing area."], ["Short-Run Bracket Set", "Fabricated Parts", "manufacturing_capability", "Cut and formed brackets produced from approved dimensions."]] },
  ] },
  { industryKey: "home-living", clients: [
    { name: "Meda Furniture Studio", tagline: "Compact furniture with room to breathe.", customer: "apartment households and small hospitality spaces", customerRequest: "Show furniture in real room context and make dimensions important without feeling technical.", paletteRequest: "beige and dark brown", paletteAdvice: "The all-neutral request felt dated; walnut remains in the material while blue-green gives the brand a crisp contemporary anchor.", colors: ["#815237", "#ebddd3", "#1f6170", "#d8e8ec"], neutral: "paper", style: "room", logoConcept: "an M built from two chair profiles", visualThesis: "Airy room scenes with close joinery and confident blue-green accents.", heroTitle: "Furniture scaled for the room you actually have.", heroSubtitle: "Compare useful pieces, dimensions, finishes, and made-to-fit options.", process: ["Measure room and use", "Choose material and finish", "Build, inspect, and place"], offerings: [["Compact Lounge Chair", "Seating", "standard_product", "A low chair with a supportive woven seat."], ["Round Side Table", "Tables", "standard_product", "A compact hardwood table for flexible placement."], ["Entry Storage Bench", "Storage", "standard_product", "A narrow bench with practical lower storage."], ["Made-to-Fit Dining Table", "Custom Furniture", "made_to_order", "A table specified by room, seating count, timber, and finish."]] },
    { name: "Tullu Timber Works", tagline: "Timber components prepared for the next maker.", customer: "carpenters, fit-out teams, and homeowners", customerRequest: "Make wood grading and cut-to-size work clear, not just show finished furniture.", paletteRequest: "wood brown and cream", paletteAdvice: "Brown-on-cream hid material variation; timber remains in photography while forest green and cobalt define service choices.", colors: ["#39744f", "#dceade", "#2858a0", "#dce5f4"], neutral: "fresh", style: "material", logoConcept: "tree rings interrupted by a clean T cut", visualThesis: "Material-first photography with measured cut and finish information.", heroTitle: "Start with timber prepared for the work ahead.", heroSubtitle: "Review boards, panels, turned parts, and cut-to-size preparation.", process: ["Select and grade timber", "Cut and condition", "Finish and bundle"], offerings: [["Graded Hardwood Boards", "Timber", "production_supply", "Selected boards grouped by practical grade and dimension."], ["Edge-Glued Worktop", "Panels", "manufacturing_capability", "A prepared solid-wood panel built to approved dimensions."], ["Turned Furniture Leg Set", "Components", "manufacturing_capability", "A repeat set of turned legs from an approved profile."], ["Cut-to-Size Timber Pack", "Prepared Material", "made_to_order", "A labeled component pack cut for a defined small project."]] },
    { name: "Buna Basket House", tagline: "Woven storage shaped for everyday rooms.", customer: "households, cafes, and gift shops", customerRequest: "Make baskets look contemporary and useful, not like souvenirs.", paletteRequest: "tan and orange", paletteAdvice: "Natural fiber already supplies tan; the interface uses crisp white, red-coral accents, and dark indigo for modern contrast.", colors: ["#c34d36", "#f2d9d2", "#3f3b7a", "#e2e0ef"], neutral: "paper", style: "atelier", logoConcept: "a woven B inside an open basket rim", visualThesis: "Graphic weave detail paired with bright modern rooms and strong object silhouettes.", heroTitle: "Woven forms that earn their place in the room.", heroSubtitle: "Browse storage, serving, planters, and coordinated small retail sets.", process: ["Choose fiber and form", "Build the woven structure", "Trim, inspect, and shape"], offerings: [["Lidded Floor Basket", "Storage", "standard_product", "A structured basket for blankets and household storage."], ["Low Serving Tray", "Table", "standard_product", "A firm woven tray with raised carrying edge."], ["Woven Planter Cover", "Decor", "standard_product", "A clean-sided cover for common indoor plant pots."], ["Retail Basket Quartet", "Wholesale", "production_supply", "Four coordinated forms supplied as a small shop set."]] },
    { name: "Kora Ceramic House", tagline: "Tableware with glaze variation left visible.", customer: "homes, cafes, and gift buyers", customerRequest: "Use color confidently but let the handmade variation feel intentional.", paletteRequest: "terracotta and cream", paletteAdvice: "Terracotta stays in the clay and mark; mineral blue creates a clearer modern counterpoint across sections.", colors: ["#b44d2f", "#f0d8cf", "#2056a8", "#d9e5f7"], neutral: "cool", style: "material", logoConcept: "a K drawn as two stacked vessel profiles", visualThesis: "Sculptural vessel portraits against architectural gray and mineral blue.", heroTitle: "Useful forms with the hand still visible.", heroSubtitle: "Compare cups, bowls, serving pieces, and small hospitality runs.", process: ["Throw or press the form", "Dry and first-fire", "Glaze, fire, and sort"], offerings: [["Everyday Cup Pair", "Drinkware", "standard_product", "Two wheel-thrown cups with natural glaze variation."], ["Wide Serving Bowl", "Serveware", "standard_product", "A generous bowl with a durable glazed interior."], ["Carved Stem Vase", "Objects", "standard_product", "A narrow vase with hand-cut surface rhythm."], ["Cafe Cup Production Run", "Hospitality", "made_to_order", "A repeat cup form in an agreed glaze and quantity."]] },
    { name: "Aster Lighting Works", tagline: "Light fixtures designed as part of the room.", customer: "homeowners, cafes, and interior designers", customerRequest: "Show the glow and the fixture together, with enough technical information to ask for a project.", paletteRequest: "gold and black", paletteAdvice: "The luxury pairing was too theatrical; amber remains the light cue while midnight blue and white make specifications easier to read.", colors: ["#b77900", "#f3e3b9", "#233f70", "#dce4f2"], neutral: "cool", style: "room", logoConcept: "an A suspended like a pendant shade", visualThesis: "Warm pools of light framed by cool architectural surfaces.", heroTitle: "A room changes when the light belongs there.", heroSubtitle: "Browse pendants, wall lights, task lighting, and coordinated project sets.", process: ["Define place and effect", "Build fixture and wiring", "Test light and finish"], offerings: [["Woven Pendant Light", "Pendants", "standard_product", "A warm pendant with a structured woven shade."], ["Directional Wall Light", "Wall Lights", "standard_product", "A compact adjustable fixture for focused light."], ["Workshop Task Lamp", "Task Lights", "standard_product", "A sturdy articulated lamp for bench work."], ["Cafe Lighting Set", "Project Lighting", "made_to_order", "A coordinated quantity inquiry by layout and finish."]] },
    { name: "Wabi Joinery Studio", tagline: "Fitted storage drawn around the wall it serves.", customer: "homeowners and small offices", customerRequest: "Lead with fitted project thinking and make the inquiry feel approachable.", paletteRequest: "sage and oak", paletteAdvice: "Sage and oak were too soft together; deep green grounds the brand and brick red creates a precise project accent.", colors: ["#b34732", "#f1d9d3", "#24583e", "#d8e8de"], neutral: "fresh", style: "room", logoConcept: "a W made from interlocking joinery shoulders", visualThesis: "Measured wall compositions with warm wood and confident architectural color.", heroTitle: "Storage that begins with the wall, not the catalog.", heroSubtitle: "Review fitted shelves, cabinets, work surfaces, and compact interior packages.", process: ["Measure the room", "Approve layout and material", "Build and fit"], offerings: [["Fitted Wall Shelving", "Storage", "made_to_order", "A measured open-shelf composition for a defined wall."], ["Compact Entry Cabinet", "Cabinetry", "made_to_order", "Closed storage configured around an entry space."], ["Window Work Desk", "Workspaces", "made_to_order", "A fitted desk sized to an available window wall."], ["Small Office Joinery Pack", "Project Joinery", "manufacturing_capability", "Repeat cabinets and work surfaces for a defined small office."]] },
    { name: "Sena Home Textiles", tagline: "Soft furnishings composed as a useful room layer.", customer: "households and small guest spaces", customerRequest: "Make it feel colorful and modern, and show how pieces coordinate without using a busy pattern background.", paletteRequest: "purple, peach, and beige", paletteAdvice: "The three soft hues felt like one fabric; saturated plum and deep teal now frame bright neutral surfaces while peach stays in product styling.", colors: ["#8d3f78", "#eedbea", "#17616a", "#d5e9eb"], neutral: "cool", style: "atelier", logoConcept: "an S folded from a ribbon-like textile", visualThesis: "Large swatches and room details on clean bands with no decorative plaid.", heroTitle: "A room palette built one useful textile at a time.", heroSubtitle: "Coordinate throws, cushions, table linen, and compact guest-room sets.", process: ["Set palette and use", "Cut, sew, and finish", "Coordinate and inspect"], offerings: [["Structured Woven Throw", "Throws", "standard_product", "A substantial throw with a controlled two-color weave."], ["Textured Cushion Pair", "Cushions", "standard_product", "Two removable covers designed to coordinate."], ["Everyday Table Runner", "Table Linen", "standard_product", "A durable runner with a clean hand-finished edge."], ["Guest Room Textile Set", "Hospitality", "made_to_order", "A coordinated textile set discussed by room count and palette."]] },
    { name: "Dara Clay Works", tagline: "Clay objects shaped for plants, tables, and daily use.", customer: "plant lovers, homes, and cafes", customerRequest: "Use the earthy material without making the whole site brown or rustic.", paletteRequest: "clay brown and sand", paletteAdvice: "Clay supplies the warmth in the images; cobalt and dark green create fresh digital contrast on white and mineral gray.", colors: ["#b44d2f", "#f0d8cf", "#245744", "#d8e8df"], neutral: "cool", style: "material", logoConcept: "a D formed by a pot profile and one handle", visualThesis: "Strong clay silhouettes presented like contemporary design objects.", heroTitle: "Clay forms made to hold, serve, and grow.", heroSubtitle: "Browse planters, table pieces, and small coordinated runs with visible variation.", process: ["Prepare and wedge clay", "Shape and refine", "Fire, finish, and sort"], offerings: [["Indoor Planter Pair", "Planters", "standard_product", "Two complementary planters with drainage."], ["Handled Water Carafe", "Tableware", "standard_product", "A hand-finished carafe with a comfortable pulled handle."], ["Low Serving Dish", "Serveware", "standard_product", "A broad dish with a durable glazed surface."], ["Cafe Tableware Run", "Hospitality", "made_to_order", "A repeat tableware form in an agreed finish and quantity."]] },
  ] },
  { industryKey: "fashion-textiles", clients: [
    { name: "Sora Workwear Studio", tagline: "Workwear cut for movement and repeat orders.", customer: "small production and service teams", customerRequest: "Show garments clearly and make team sizing and repeat orders feel organized.", paletteRequest: "navy and khaki", paletteAdvice: "Khaki is kept in garment photography, while crisp white, navy, and safety red make the interface more decisive.", colors: ["#bd4038", "#f0d8d5", "#244d78", "#dbe5f0"], neutral: "cool", style: "precision", logoConcept: "an S built from two reinforced seam lines", visualThesis: "Uniform silhouettes and construction details arranged with production discipline.", heroTitle: "A uniform should be easy to move in and easy to reorder.", heroSubtitle: "Compare core garments, pocket layouts, branding, and team production options.", process: ["Choose garment and sizing", "Cut and assemble", "Fit-check and record"], offerings: [["Production Work Shirt", "Work Shirts", "standard_product", "A durable shirt with practical reinforced pockets."], ["Cross-Back Workshop Apron", "Aprons", "standard_product", "An adjustable apron designed to distribute weight."], ["Service Team Trouser", "Trousers", "standard_product", "A repeat trouser with functional pocket placement."], ["Branded Team Uniform Run", "Team Orders", "manufacturing_capability", "A sized repeat garment program with approved branding."]] },
    { name: "Liya Textile House", tagline: "Woven cloth selected by hand, weight, and use.", customer: "designers, tailors, and households", customerRequest: "Present cloth as material, not finished fashion, and make swatches easy to compare.", paletteRequest: "burgundy and cream", paletteAdvice: "Cream made swatches blend into the page; burgundy remains the mark while cobalt and clean gray separate product families.", colors: ["#92374e", "#eed9df", "#2856a0", "#dce4f4"], neutral: "cool", style: "atelier", logoConcept: "an L drawn by one folded fabric edge", visualThesis: "Large tactile swatches with disciplined labels and sharp color contrast.", heroTitle: "Choose the cloth by how it needs to live.", heroSubtitle: "Compare weight, texture, color run, and intended use before asking about length.", process: ["Set fiber and hand", "Weave the color run", "Inspect, finish, and roll"], offerings: [["Midweight Cotton Cloth", "Cotton", "production_supply", "A versatile woven cotton sold by requested length."], ["Textured Interior Weave", "Interior Textiles", "production_supply", "A heavier cloth for cushions and soft furnishings."], ["Light Garment Stripe", "Garment Cloth", "production_supply", "A lighter striped cloth for shirts and relaxed garments."], ["Custom Color Weave Run", "Custom Weaving", "made_to_order", "A small woven run developed around an approved palette."]] },
    { name: "Biftu Leather Goods", tagline: "Leather carry goods with the construction in view.", customer: "working adults and practical gift buyers", customerRequest: "Make the bags feel durable and modern without a dark brown luxury site.", paletteRequest: "brown and black", paletteAdvice: "Leather already provides brown; indigo and berry create a contemporary interface while black is reserved for the inverse close.", colors: ["#3d59b7", "#dce3f6", "#a23d55", "#efd9df"], neutral: "cool", style: "material", logoConcept: "a B made from two stitched pocket curves", visualThesis: "Construction close-ups framed by bold, cool editorial color.", heroTitle: "Carry goods that show how they are held together.", heroSubtitle: "Inspect seams, closures, capacity, and finish before asking about a piece or team run.", process: ["Select hide and pattern", "Cut and prepare edges", "Stitch, finish, and inspect"], offerings: [["Structured Work Tote", "Bags", "standard_product", "A reinforced open tote with an exterior tool pocket."], ["Everyday Crossbody", "Bags", "standard_product", "A secure medium satchel with an adjustable strap."], ["Slim Card Wallet", "Small Goods", "standard_product", "A compact wallet with visible edge finishing."], ["Branded Staff Carry Set", "Team Orders", "made_to_order", "A coordinated small run of practical carry goods."]] },
    { name: "Meda Uniform Works", tagline: "Repeat uniforms with fit records kept clear.", customer: "schools, clinics, cafes, and service teams", customerRequest: "Make the workflow feel reliable for coordinators ordering many sizes.", paletteRequest: "royal blue and white", paletteAdvice: "Royal blue remains recognizable, while a dark green secondary distinguishes fitting, production, and inquiry states.", colors: ["#315cc4", "#dce5fa", "#205b48", "#d8e8e0"], neutral: "cool", style: "precision", logoConcept: "an M assembled from three garment pattern notches", visualThesis: "Sizing order and garment clarity presented like a calm production system.", heroTitle: "A repeat uniform begins with a reliable size record.", heroSubtitle: "Choose a garment family and discuss fitting, branding, quantity, and reorder continuity.", process: ["Fit and record sizes", "Approve sample garment", "Produce, sort, and label"], offerings: [["Service Polo Shirt", "Service Uniforms", "manufacturing_capability", "A repeat polo program with size and marking options."], ["Clinic Tunic", "Clinic Uniforms", "manufacturing_capability", "A practical tunic produced in an approved fabric and size set."], ["School Sweater", "School Uniforms", "manufacturing_capability", "A repeat sweater order organized by recorded sizes."], ["Uniform Reorder Program", "Repeat Orders", "production_supply", "A retained style and sizing workflow for future team needs."]] },
    { name: "Kora Weaving Studio", tagline: "Woven pieces built through color, rhythm, and touch.", customer: "homes, designers, and gift buyers", customerRequest: "Make the site expressive and artistic but keep products readable on a phone.", paletteRequest: "many traditional bright colors", paletteAdvice: "The full rainbow belongs in the textiles, not every surface; magenta and deep blue anchor a white gallery so each weave can lead.", colors: ["#b52b70", "#f3d6e5", "#30438a", "#dfe3f3"], neutral: "cool", style: "atelier", logoConcept: "a K formed by crossing warp and weft bands", visualThesis: "Expressive cloth in a disciplined gallery with gentle reveal motion.", heroTitle: "Color finds its rhythm at the loom.", heroSubtitle: "Explore wraps, runners, cushions, and custom woven color studies.", process: ["Compose the palette", "Set warp and rhythm", "Weave and hand-finish"], offerings: [["Graphic Cotton Wrap", "Wearable Textiles", "standard_product", "A handwoven wrap with a strong controlled color rhythm."], ["Long Table Runner", "Table Textiles", "standard_product", "A durable runner with a hand-finished edge."], ["Woven Cushion Face", "Interior Textiles", "standard_product", "A textured front panel prepared for a standard cushion insert."], ["Custom Palette Weave", "Custom Work", "made_to_order", "A small textile run developed from an approved color study."]] },
    { name: "Ayni Garment Room", tagline: "Made-to-measure clothing with a calm fitting process.", customer: "women seeking everyday and occasion garments", customerRequest: "Make it personal and elegant, with the fitting process visible and no bridal-site clichés.", paletteRequest: "blush pink and gold", paletteAdvice: "Blush and gold felt predictable and low contrast; plum carries warmth while deep teal and white make the fitting journey contemporary.", colors: ["#93406f", "#eedbe8", "#17616a", "#d5e9eb"], neutral: "paper", style: "atelier", logoConcept: "an A shaped by a draped neckline", visualThesis: "Quiet drape, precise fit, and jewel-toned editorial restraint.", heroTitle: "A garment shaped around the person wearing it.", heroSubtitle: "Review silhouettes and begin with occasion, fabric, measurements, and timing.", process: ["Choose silhouette and cloth", "Measure and fit", "Finish and final-check"], offerings: [["Relaxed Day Dress", "Dresses", "made_to_order", "A simple made-to-measure dress for everyday wear."], ["Draped Occasion Set", "Occasion Wear", "made_to_order", "A coordinated garment set developed through fitting."], ["Tailored Long Jacket", "Outer Layers", "made_to_order", "A lined long jacket shaped to the wearer."], ["Small Group Garment Run", "Group Orders", "manufacturing_capability", "A coordinated garment run from one approved pattern."]] },
    { name: "Tana Cloth House", tagline: "Practical cloth and coordinated household sets.", customer: "households, tailors, and small retailers", customerRequest: "Show the breadth without turning the page into a crowded fabric shop.", paletteRequest: "teal, orange, and cream", paletteAdvice: "Teal and orange remain but sit on crisp white and cool gray, giving the products more separation than a cream base.", colors: ["#c9592c", "#f3ddd3", "#17616a", "#d5e9eb"], neutral: "cool", style: "utility", logoConcept: "a folded T made from a measured cloth roll", visualThesis: "A clean shelf of cloth families with strong color-coded navigation.", heroTitle: "Cloth choices organized by the work ahead.", heroSubtitle: "Browse garment, household, and interior fabrics without losing track of weight and use.", process: ["Choose use and weight", "Confirm color and length", "Cut, label, and prepare"], offerings: [["Everyday Garment Cotton", "Garment Cloth", "production_supply", "A versatile cotton cloth supplied by requested length."], ["Durable Sheet Fabric", "Household Cloth", "production_supply", "A practical wider cloth for sheets and household sewing."], ["Textured Curtain Cloth", "Interior Cloth", "production_supply", "A medium-weight fabric with a subtle woven texture."], ["Coordinated Home Cloth Pack", "Household Sets", "made_to_order", "A matched cloth selection for several household uses."]] },
    { name: "Zema Bag Studio", tagline: "Bags designed around what needs to be carried.", customer: "commuters, students, and small teams", customerRequest: "Make the products feel energetic and urban while showing pockets and capacity clearly.", paletteRequest: "orange and black", paletteAdvice: "Black is reserved for the footer and product detail; coral and cobalt create a clearer, more flexible brand system.", colors: ["#d25236", "#f4dcd5", "#3158b0", "#dce4f6"], neutral: "cool", style: "room", logoConcept: "a zip line drawing a sharp Z", visualThesis: "Dynamic carry silhouettes with clear exploded pocket details.", heroTitle: "Start with what the bag needs to carry.", heroSubtitle: "Compare daily bags by capacity, access, and construction, or brief a small team run.", process: ["Map the carry need", "Cut and assemble", "Load-test and finish"], offerings: [["Daily Zip Tote", "Totes", "standard_product", "A structured tote with secure top zip and bottle pocket."], ["Compact Commuter Backpack", "Backpacks", "standard_product", "A clean backpack with padded device space."], ["Crossbody Utility Pouch", "Small Bags", "standard_product", "A compact adjustable pouch with divided storage."], ["Team Field Bag Run", "Team Orders", "manufacturing_capability", "A repeat bag built from one approved pocket and branding brief."]] },
  ] },
];

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function foundationReason(style: StyleKey) {
  const profile = styleProfiles[style];
  return `${profile.tokenPack} supplies the typography, spacing, geometry, and media behavior because the brief fits ${style.replace("_", " ")} content anatomy; the palette is independently authored from the brand direction.`;
}

export const SCALE_DEMO_BUSINESSES: readonly ScaleDemoBusiness[] = clientGroups.flatMap(
  ({ industryKey, clients }, groupIndex) => clients.map((raw, index) => {
    const handle = `demo-${slug(raw.name)}`;
    const location = locations[locationPlans[industryKey][index]];
    const customPalette = palette(raw);
    const profile: SeedShowroomBrief["profile"] = {
      ...styleProfiles[raw.style],
      customPalette,
    };
    const description = `${raw.tagline} This fictional ${raw.name} showroom is designed for ${raw.customer}.`;
    return {
      handle,
      name: raw.name,
      tagline: raw.tagline,
      description,
      heroTitle: raw.heroTitle,
      heroSubtitle: raw.heroSubtitle,
      industryKey,
      logoPath: `/uploads/seed/portfolio/${handle}/logo.svg`,
      heroPath: `/uploads/seed/portfolio/${handle}/hero.webp`,
      boothPath: `/landing/showroom-booths/${handle}.svg`,
      profile: {
        ...location,
        industryKeys: [industryKey],
        latitude: location.latitude + groupIndex * 0.0004 + index * 0.0001,
        longitude: location.longitude + groupIndex * 0.0004 + index * 0.0001,
      },
      brief: {
        objective: raw.customerRequest,
        template: `${raw.visualThesis} Preserve the canonical story, process, offering, and inquiry journey.`,
        profile,
        story: {
          kicker: "Inside the work",
          title: raw.visualThesis,
          quote: raw.tagline,
        },
        process: {
          title: `How ${raw.name} takes the work from question to handoff`,
          body: "The fictional process is provisional demonstration copy and is reviewed with a real customer before use.",
          items: [...raw.process],
        },
        cta: {
          title: `Ask ${raw.name} about the closest fit.`,
          body: "Add an offering and share the use, preferred format, timing, and optional quantity in one direct inquiry.",
        },
      },
      creative: {
        customer: raw.customer,
        customerRequest: raw.customerRequest,
        paletteRequest: raw.paletteRequest,
        paletteAdvice: raw.paletteAdvice,
        logoConcept: raw.logoConcept,
        visualThesis: raw.visualThesis,
        foundationReason: foundationReason(raw.style),
      },
      offerings: raw.offerings.map(([name, category, kind, offeringDescription], offeringIndex) => ({
        name,
        category,
        kind,
        description: offeringDescription,
        imagePath: `/uploads/seed/portfolio/${handle}/product-${offeringIndex + 1}.webp`,
      })),
    } satisfies ScaleDemoBusiness;
  }),
);

export function scaleDemoBusiness(handle: string) {
  return SCALE_DEMO_BUSINESSES.find((business) => business.handle === handle);
}
