import crypto from "node:crypto";
import fs from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { Client } from "pg";
import { databasePath } from "../lib/config";
import {
  POSTGRES_TRIGGER_NAMES,
  postgresTriggerDefinitions,
} from "./postgres-trigger-definitions";

type SqliteTable = { name: string; sql: string };
type SqliteColumn = {
  cid: number;
  name: string;
  type: string;
  notnull: number;
  dflt_value: string | null;
  pk: number;
};
type SqliteForeignKey = {
  id: number;
  seq: number;
  table: string;
  from: string;
  to: string;
  on_update: string;
  on_delete: string;
  match: string;
};
type SqliteIndex = {
  seq: number;
  name: string;
  unique: number;
  origin: "c" | "u" | "pk";
  partial: number;
};
type SqliteIndexColumn = {
  seqno: number;
  cid: number;
  name: string | null;
  desc: number;
  key: number;
};

const TARGET_SCHEMA_PATTERN = /^mirtpage_rehearsal(?:_[a-z0-9_]+)?$/;
const POSTGRES_URL = process.env.MIRTPAGE_POSTGRES_REHEARSAL_URL || "";
const TARGET_SCHEMA = process.env.MIRTPAGE_POSTGRES_REHEARSAL_SCHEMA || "mirtpage_rehearsal";
const RESET_TARGET = process.argv.includes("--reset-target");
const INSERT_BATCH_SIZE = 200;

function q(identifier: string) {
  if (!/^[a-z_][a-z0-9_]*$/i.test(identifier)) {
    throw new Error("The database schema contains an unsupported identifier.");
  }
  return `"${identifier}"`;
}

function qualified(schema: string, table: string) {
  return `${q(schema)}.${q(table)}`;
}

function sqliteColumns(db: DatabaseSync, table: string) {
  return db.prepare(`PRAGMA table_info(${q(table)})`).all() as SqliteColumn[];
}

function sqliteForeignKeys(db: DatabaseSync, table: string) {
  return db.prepare(`PRAGMA foreign_key_list(${q(table)})`).all() as SqliteForeignKey[];
}

function extractChecks(sql: string) {
  const checks: string[] = [];
  let cursor = 0;
  while (cursor < sql.length) {
    const match = /\bCHECK\s*\(/gi.exec(sql.slice(cursor));
    if (!match) break;
    const open = cursor + match.index + match[0].lastIndexOf("(");
    let depth = 1;
    let quote: "'" | '"' | null = null;
    let index = open + 1;
    for (; index < sql.length && depth > 0; index += 1) {
      const character = sql[index];
      if (quote) {
        if (character === quote) {
          if (sql[index + 1] === quote) index += 1;
          else quote = null;
        }
        continue;
      }
      if (character === "'" || character === '"') {
        quote = character;
      } else if (character === "(") {
        depth += 1;
      } else if (character === ")") {
        depth -= 1;
      }
    }
    if (depth !== 0) throw new Error("Could not parse a SQLite CHECK constraint.");
    const expression = sql.slice(open + 1, index - 1).trim();
    if (!expression || /;|--|\/\*/.test(expression)) {
      throw new Error("The SQLite schema contains an unsafe CHECK constraint.");
    }
    checks.push(
      expression.replace(
        /json_valid\(\s*([a-z_][a-z0-9_]*)\s*\)/gi,
        "$1 IS JSON",
      ),
    );
    cursor = index;
  }
  return checks;
}

function postgresType(type: string) {
  const normalized = type.trim().toUpperCase();
  if (!normalized || normalized.includes("TEXT") || normalized.includes("CHAR")) return "text";
  if (normalized.includes("INT")) return "bigint";
  if (normalized.includes("REAL") || normalized.includes("FLOA") || normalized.includes("DOUB")) {
    return "double precision";
  }
  if (normalized.includes("BLOB")) return "bytea";
  throw new Error(`Unsupported SQLite type ${type}.`);
}

function postgresDefault(value: string | null) {
  if (value === null) return "";
  const safe =
    /^NULL$/i.test(value) ||
    /^CURRENT_TIMESTAMP$/i.test(value) ||
    /^-?\d+(?:\.\d+)?$/.test(value) ||
    /^'(?:''|[^'])*'$/.test(value);
  if (!safe) throw new Error("The SQLite schema contains an unsupported default expression.");
  return ` DEFAULT ${value}`;
}

function createTableSql(table: SqliteTable, columns: SqliteColumn[], schema: string) {
  const primary = columns.filter((column) => column.pk > 0).sort((a, b) => a.pk - b.pk);
  const identityColumn =
    primary.length === 1 && /\bAUTOINCREMENT\b/i.test(table.sql)
      ? primary[0].name
      : null;
  const definitions = columns.map((column) => {
    const type = postgresType(column.type);
    const identity = column.name === identityColumn
      ? " GENERATED BY DEFAULT AS IDENTITY"
      : "";
    const notNull = column.notnull || column.pk ? " NOT NULL" : "";
    return `  ${q(column.name)} ${type}${identity}${notNull}${postgresDefault(column.dflt_value)}`;
  });
  if (primary.length) {
    definitions.push(
      `  CONSTRAINT ${q(`pk_${table.name}`)} PRIMARY KEY (${primary.map((column) => q(column.name)).join(", ")})`,
    );
  }
  extractChecks(table.sql).forEach((check, index) => {
    definitions.push(
      `  CONSTRAINT ${q(`ck_${table.name}_${index + 1}`)} CHECK (${check})`,
    );
  });
  return `CREATE TABLE ${qualified(schema, table.name)} (\n${definitions.join(",\n")}\n);`;
}

function groupedForeignKeys(rows: SqliteForeignKey[]) {
  const groups = new Map<number, SqliteForeignKey[]>();
  for (const row of rows) {
    const group = groups.get(row.id) || [];
    group.push(row);
    groups.set(row.id, group);
  }
  return [...groups.entries()].map(([id, group]) => ({
    id,
    rows: group.sort((left, right) => left.seq - right.seq),
  }));
}

function foreignKeySql(table: string, foreignKey: ReturnType<typeof groupedForeignKeys>[number], schema: string) {
  const target = foreignKey.rows[0].table;
  const onDelete = foreignKey.rows[0].on_delete;
  const onUpdate = foreignKey.rows[0].on_update;
  const action = (value: string) => {
    const normalized = value.replace(/_/g, " ").toUpperCase();
    return ["NO ACTION", "RESTRICT", "CASCADE", "SET NULL", "SET DEFAULT"].includes(normalized)
      ? normalized
      : "NO ACTION";
  };
  return `ALTER TABLE ${qualified(schema, table)} ADD CONSTRAINT ${q(`fk_${table}_${foreignKey.id}`)} FOREIGN KEY (${foreignKey.rows.map((row) => q(row.from)).join(", ")}) REFERENCES ${qualified(schema, target)} (${foreignKey.rows.map((row) => q(row.to)).join(", ")}) ON UPDATE ${action(onUpdate)} ON DELETE ${action(onDelete)};`;
}

function sourceIndexSql(db: DatabaseSync, indexName: string) {
  return (db.prepare("SELECT sql FROM sqlite_master WHERE type='index' AND name=?").get(indexName) as { sql: string | null } | undefined)?.sql || null;
}

function postgresIndexes(db: DatabaseSync, table: string, schema: string) {
  const indexes = db.prepare(`PRAGMA index_list(${q(table)})`).all() as SqliteIndex[];
  return indexes
    .filter((index) => index.origin !== "pk")
    .map((index, position) => {
      const columns = (db.prepare(`PRAGMA index_xinfo(${q(index.name)})`).all() as SqliteIndexColumn[])
        .filter((column) => column.key === 1)
        .sort((left, right) => left.seqno - right.seqno);
      if (!columns.length || columns.some((column) => !column.name)) {
        throw new Error(`Index ${index.name} uses an unsupported expression.`);
      }
      const original = sourceIndexSql(db, index.name);
      const predicateMatch = original?.match(/\bWHERE\b([\s\S]+)$/i);
      const predicate = predicateMatch?.[1].trim() || "";
      if (predicate && /;|--|\/\*/.test(predicate)) {
        throw new Error(`Index ${index.name} has an unsafe predicate.`);
      }
      const generatedName = index.name.startsWith("sqlite_autoindex_")
        ? `uq_${table}_${position + 1}`
        : index.name;
      return `CREATE ${index.unique ? "UNIQUE " : ""}INDEX ${q(generatedName)} ON ${qualified(schema, table)} (${columns.map((column) => `${q(column.name!)}${column.desc ? " DESC" : ""}`).join(", ")})${predicate ? ` WHERE ${predicate}` : ""};`;
    });
}

function normalizedRow(row: Record<string, unknown>, columns: string[]) {
  return JSON.stringify(
    columns.map((column) => {
      const value = row[column];
      if (value === null || value === undefined) return null;
      if (Buffer.isBuffer(value)) return `base64:${value.toString("base64")}`;
      return String(value);
    }),
  );
}

function fingerprint(rows: Record<string, unknown>[], columns: string[]) {
  const hash = crypto.createHash("sha256");
  rows.map((row) => normalizedRow(row, columns)).sort().forEach((row) => {
    hash.update(row);
    hash.update("\n");
  });
  return hash.digest("hex");
}

async function insertRows(
  client: Client,
  table: string,
  columns: string[],
  rows: Record<string, unknown>[],
  schema: string,
) {
  for (let offset = 0; offset < rows.length; offset += INSERT_BATCH_SIZE) {
    const batch = rows.slice(offset, offset + INSERT_BATCH_SIZE);
    const values = batch.flatMap((row) => columns.map((column) => row[column]));
    const tuples = batch.map((_, rowIndex) =>
      `(${columns.map((__, columnIndex) => `$${rowIndex * columns.length + columnIndex + 1}`).join(", ")})`,
    );
    await client.query(
      `INSERT INTO ${qualified(schema, table)} (${columns.map(q).join(", ")}) VALUES ${tuples.join(", ")}`,
      values,
    );
  }
}

async function expectPostgresRejection(
  client: Client,
  sql: string,
  expectedCode: string,
) {
  await client.query("SAVEPOINT invariant_probe");
  try {
    await client.query(sql);
    throw new Error("A PostgreSQL invariant probe was unexpectedly accepted.");
  } catch (error) {
    const code = (error as { code?: string }).code;
    if (code !== expectedCode) throw error;
  } finally {
    await client.query("ROLLBACK TO SAVEPOINT invariant_probe");
    await client.query("RELEASE SAVEPOINT invariant_probe");
  }
}

async function main() {
  if (!POSTGRES_URL) throw new Error("MIRTPAGE_POSTGRES_REHEARSAL_URL is required.");
  const parsed = new URL(POSTGRES_URL);
  if (!/^postgres(?:ql)?:$/.test(parsed.protocol) || parsed.password.length < 8) {
    throw new Error("The PostgreSQL rehearsal URL is invalid.");
  }
  if (!TARGET_SCHEMA_PATTERN.test(TARGET_SCHEMA)) {
    throw new Error("The rehearsal schema must begin with mirtpage_rehearsal.");
  }

  const sourcePath = databasePath();
  const sourceBefore = crypto.createHash("sha256").update(fs.readFileSync(sourcePath)).digest("hex");
  const source = new DatabaseSync(sourcePath, { readOnly: true });
  const target = new Client({ connectionString: POSTGRES_URL });
  try {
    const integrity = source.prepare("PRAGMA integrity_check").get() as { integrity_check: string };
    if (integrity.integrity_check !== "ok") throw new Error("SQLite source integrity check failed.");
    const tables = source.prepare(`
      SELECT name,sql FROM sqlite_master
      WHERE type='table' AND name NOT LIKE 'sqlite_%'
      ORDER BY name
    `).all() as SqliteTable[];
    const sourceTriggers = (source.prepare(`
      SELECT name FROM sqlite_master WHERE type='trigger' ORDER BY name
    `).all() as Array<{ name: string }>).map((row) => row.name);
    if (sourceTriggers.join("\n") !== [...POSTGRES_TRIGGER_NAMES].sort().join("\n")) {
      throw new Error("The PostgreSQL trigger translation is not synchronized with SQLite.");
    }

    await target.connect();
    await target.query("BEGIN");
    const existing = await target.query<{ count: string }>(
      "SELECT count(*)::text count FROM information_schema.tables WHERE table_schema=$1",
      [TARGET_SCHEMA],
    );
    if (Number(existing.rows[0].count) && !RESET_TARGET) {
      throw new Error("The rehearsal target schema is not empty. Use --reset-target for a disposable target.");
    }
    if (RESET_TARGET) await target.query(`DROP SCHEMA IF EXISTS ${q(TARGET_SCHEMA)} CASCADE`);
    await target.query(`CREATE SCHEMA ${q(TARGET_SCHEMA)}`);

    let expectedChecks = 0;
    let expectedForeignKeys = 0;
    let expectedIndexes = 0;
    let totalRows = 0;
    const sourceRows = new Map<string, Record<string, unknown>[]>();
    const tableColumns = new Map<string, string[]>();

    for (const table of tables) {
      const columns = sqliteColumns(source, table.name);
      expectedChecks += extractChecks(table.sql).length;
      await target.query(createTableSql(table, columns, TARGET_SCHEMA));
      const names = columns.map((column) => column.name);
      tableColumns.set(table.name, names);
      const rows = source.prepare(
        `SELECT ${names.map(q).join(", ")} FROM ${q(table.name)}`,
      ).all() as Record<string, unknown>[];
      sourceRows.set(table.name, rows);
      totalRows += rows.length;
      await insertRows(target, table.name, names, rows, TARGET_SCHEMA);
    }

    for (const table of tables) {
      const indexes = postgresIndexes(source, table.name, TARGET_SCHEMA);
      expectedIndexes += indexes.length;
      for (const sql of indexes) await target.query(sql);
    }
    for (const table of tables) {
      const foreignKeys = groupedForeignKeys(sqliteForeignKeys(source, table.name));
      expectedForeignKeys += foreignKeys.length;
      for (const foreignKey of foreignKeys) {
        await target.query(foreignKeySql(table.name, foreignKey, TARGET_SCHEMA));
      }
    }

    for (const table of tables) {
      const columns = sqliteColumns(source, table.name);
      const primary = columns.filter((column) => column.pk > 0);
      if (primary.length !== 1 || !/\bAUTOINCREMENT\b/i.test(table.sql)) continue;
      const column = primary[0].name;
      await target.query(
        `SELECT setval(pg_get_serial_sequence($1,$2), COALESCE((SELECT max(${q(column)}) FROM ${qualified(TARGET_SCHEMA, table.name)}), 1), EXISTS(SELECT 1 FROM ${qualified(TARGET_SCHEMA, table.name)}))`,
        [`${TARGET_SCHEMA}.${table.name}`, column],
      );
    }

    await target.query(postgresTriggerDefinitions(TARGET_SCHEMA));

    for (const table of tables) {
      const columns = tableColumns.get(table.name)!;
      const targetResult = await target.query<Record<string, unknown>>(
        `SELECT ${columns.map(q).join(", ")} FROM ${qualified(TARGET_SCHEMA, table.name)}`,
      );
      const expected = sourceRows.get(table.name)!;
      if (
        targetResult.rows.length !== expected.length ||
        fingerprint(targetResult.rows, columns) !== fingerprint(expected, columns)
      ) {
        throw new Error(`PostgreSQL row reconciliation failed for ${table.name}.`);
      }
    }

    const targetCounts = await target.query<{
      tables: string;
      checks: string;
      foreign_keys: string;
      indexes: string;
      triggers: string;
      not_null_columns: string;
    }>(`
      SELECT
        (SELECT count(*) FROM information_schema.tables WHERE table_schema=$1)::text tables,
        (SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname=$1 AND c.contype='c')::text checks,
        (SELECT count(*) FROM pg_constraint c JOIN pg_namespace n ON n.oid=c.connamespace WHERE n.nspname=$1 AND c.contype='f')::text foreign_keys,
        (SELECT count(*) FROM pg_index i JOIN pg_class t ON t.oid=i.indrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname=$1 AND NOT i.indisprimary)::text indexes,
        (SELECT count(*) FROM pg_trigger g JOIN pg_class t ON t.oid=g.tgrelid JOIN pg_namespace n ON n.oid=t.relnamespace WHERE n.nspname=$1 AND NOT g.tgisinternal)::text triggers,
        (SELECT count(*) FROM information_schema.columns WHERE table_schema=$1 AND is_nullable='NO')::text not_null_columns
    `, [TARGET_SCHEMA]);
    const expectedNotNull = tables.reduce(
      (count, table) => count + sqliteColumns(source, table.name).filter((column) => column.notnull || column.pk).length,
      0,
    );
    const counts = targetCounts.rows[0];
    if (
      Number(counts.tables) !== tables.length ||
      Number(counts.checks) !== expectedChecks ||
      Number(counts.foreign_keys) !== expectedForeignKeys ||
      Number(counts.indexes) !== expectedIndexes ||
      Number(counts.triggers) !== sourceTriggers.length ||
      Number(counts.not_null_columns) !== expectedNotNull
    ) {
      throw new Error("PostgreSQL schema reconciliation failed.");
    }

    await expectPostgresRejection(
      target,
      `UPDATE ${qualified(TARGET_SCHEMA, "businesses")} SET status='invalid' WHERE id=(SELECT min(id) FROM ${qualified(TARGET_SCHEMA, "businesses")})`,
      "23514",
    );
    await expectPostgresRejection(
      target,
      `UPDATE ${qualified(TARGET_SCHEMA, "users")} SET business_id=-1 WHERE id=(SELECT min(id) FROM ${qualified(TARGET_SCHEMA, "users")})`,
      "23503",
    );
    await expectPostgresRejection(
      target,
      `UPDATE ${qualified(TARGET_SCHEMA, "businesses")} SET handle=(SELECT handle FROM ${qualified(TARGET_SCHEMA, "businesses")} ORDER BY id LIMIT 1) WHERE id=(SELECT max(id) FROM ${qualified(TARGET_SCHEMA, "businesses")})`,
      "23505",
    );
    await expectPostgresRejection(
      target,
      `UPDATE ${qualified(TARGET_SCHEMA, "content_revisions")} SET summary=summary WHERE id=(SELECT id FROM ${qualified(TARGET_SCHEMA, "content_revisions")} WHERE status<>'draft' ORDER BY id LIMIT 1)`,
      "23514",
    );

    await target.query("COMMIT");
    const sourceAfter = crypto.createHash("sha256").update(fs.readFileSync(sourcePath)).digest("hex");
    if (sourceBefore !== sourceAfter) throw new Error("The SQLite source changed during rehearsal.");
    console.log(JSON.stringify({
      source: "sqlite-read-only",
      target: "postgresql-rehearsal-schema",
      schema: TARGET_SCHEMA,
      tables: tables.length,
      rows: totalRows,
      checks: expectedChecks,
      foreignKeys: expectedForeignKeys,
      indexes: expectedIndexes,
      triggers: sourceTriggers.length,
      notNullColumns: expectedNotNull,
      fingerprintsReconciled: tables.length,
      invariantsProbed: 4,
      sourceBytePreserved: true,
      runtimeCutoverEnabled: false,
    }));
  } catch (error) {
    await target.query("ROLLBACK").catch(() => undefined);
    throw error;
  } finally {
    source.close();
    await target.end().catch(() => undefined);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : "PostgreSQL rehearsal failed.");
  process.exit(1);
});
