import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";
async function main(){
const root=fs.mkdtempSync(path.join(os.tmpdir(),"mirtpage-test-"));process.env.MIRTPAGE_DB_PATH=path.join(root,"test.db");process.env.MIRTPAGE_MEDIA_ROOT=path.join(root,"media");process.env.PRIVACY_SALT="test-privacy-salt-that-is-long-enough";process.env.NEXT_PUBLIC_APP_URL="https://mirtpage.test";process.env.MIRTPAGE_SERVER_ACTION_ORIGINS="http://127.0.0.1:4567,*.unsafe.test";process.env.CODESPACE_NAME="trusted-codespace";process.env.GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN="app.github.dev";
const {getDb,closeDbForTests,getBusinessByHandle}=await import("../lib/db");const {assertSameOrigin}=await import("../lib/security");const {trustedOriginPolicy}=await import("../lib/trusted-origins");const {createPublicInquiry,InquiryError}=await import("../lib/inquiries");const {verifyImage,saveUploadedImage}=await import("../lib/media");const db=getDb();
const {canMaintainBasicProducts,hasCapability}=await import("../lib/capabilities");const profile=(access_role:"platform_admin"|"operations_manager"|"team_member"|"client")=>({id:1,email:"role@example.test",name:"Role",role:access_role==="client"?"owner" as const:"admin" as const,access_role,business_id:access_role==="client"?1:null,must_change_password:0});assert.equal(hasCapability(profile("platform_admin"),"design-bank:view"),true);assert.equal(hasCapability(profile("operations_manager"),"design-bank:view"),true);assert.equal(hasCapability(profile("team_member"),"design-bank:view"),true);assert.equal(hasCapability(profile("client"),"design-bank:view"),false);assert.equal(canMaintainBasicProducts(profile("client"),1),true);assert.equal(canMaintainBasicProducts(profile("client"),2),false);assert.equal(canMaintainBasicProducts(profile("team_member"),1,true),true);assert.equal(canMaintainBasicProducts(profile("team_member"),1,false),false);
const a=Number(db.prepare("INSERT INTO businesses(handle,name,design_key,status) VALUES('a','A','novatech','active')").run().lastInsertRowid),b=Number(db.prepare("INSERT INTO businesses(handle,name,design_key,status) VALUES('b','B','homevibe','draft')").run().lastInsertRowid);const ca=Number(db.prepare("INSERT INTO collections(business_id,name,slug) VALUES(?,?,'a')").run(a,"A").lastInsertRowid),cb=Number(db.prepare("INSERT INTO collections(business_id,name,slug) VALUES(?,?,'b')").run(b,"B").lastInsertRowid);const catA=Number(db.prepare("INSERT INTO categories(business_id,collection_id,name,slug) VALUES(?,?,?,'cat-a')").run(a,ca,"Cat A").lastInsertRowid);
assert.throws(()=>db.prepare("INSERT INTO products(business_id,collection_id,name,slug) VALUES(?,?,?,'bad')").run(a,cb,"Bad"),/does not belong/);
const productId=Number(db.prepare("INSERT INTO products(business_id,collection_id,category_id,name,slug,is_published,availability) VALUES(?,?,?,?,?,1,'available')").run(a,ca,catA,"Phone","phone").lastInsertRowid);const groupId=Number(db.prepare("INSERT INTO option_groups(product_id,name,position) VALUES(?,? ,0)").run(productId,"Color").lastInsertRowid);db.prepare("INSERT INTO option_values(option_group_id,value) VALUES(?,?)").run(groupId,"Black");
assert.equal(getBusinessByHandle("b"),undefined);assert.doesNotThrow(()=>assertSameOrigin(new Request("https://mirtpage.test/api/test",{headers:{origin:"https://mirtpage.test"}})));assert.doesNotThrow(()=>assertSameOrigin(new Request("https://mirtpage.test/api/test",{headers:{origin:"http://127.0.0.1:4567"}})));assert.doesNotThrow(()=>assertSameOrigin(new Request("http://localhost:3000/api/test",{headers:{origin:"https://trusted-codespace-3000.app.github.dev"}})));assert.doesNotThrow(()=>assertSameOrigin(new Request("http://localhost:3001/api/test",{headers:{origin:"https://trusted-codespace-3001.app.github.dev"}})));assert.throws(()=>assertSameOrigin(new Request("http://localhost:3000/api/test",{headers:{origin:"https://trusted-codespace-3002.app.github.dev"}})),/Invalid request origin/);assert.throws(()=>assertSameOrigin(new Request("http://localhost:3000/api/test",{headers:{origin:"https://trusted-codespace-3000.app.github.dev.attacker.test"}})),/Invalid request origin/);assert.throws(()=>assertSameOrigin(new Request("http://localhost:3000/api/test",{headers:{origin:"https://attacker.test","x-forwarded-host":"trusted-codespace-3000.app.github.dev"}})),/Invalid request origin/);assert.throws(()=>assertSameOrigin(new Request("https://mirtpage.test/api/test",{headers:{origin:"https://attacker.test"}})),/Invalid request origin/);assert.equal(trustedOriginPolicy(process.env).serverActionHosts.some((host)=>host.includes("*")),false);assert.equal(trustedOriginPolicy({...process.env,NODE_ENV:"production"}).mutationOrigins.includes("https://trusted-codespace-3000.app.github.dev"),false);
const quantityOptionalInquiry=await createPublicInquiry({businessId:a,customerName:"X",contact:"+251 91 123 4567",contactMethod:"phone",idempotencyKey:"abcdefghij122",items:[{productId,quantity:"1 ton",options:{Color:"Black"}}]},"ip0");const quantityOptionalLine=db.prepare("SELECT quantity,quantity_intent,quantity_mode_snapshot FROM inquiry_items WHERE inquiry_id=?").get(quantityOptionalInquiry.inquiryId) as any;assert.deepEqual({...quantityOptionalLine},{quantity:null,quantity_intent:"1 ton",quantity_mode_snapshot:"optional"});assert.equal((db.prepare("SELECT contact FROM inquiries WHERE id=?").get(quantityOptionalInquiry.inquiryId) as any).contact,"+251911234567");
await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"X",contact:"+251911234567",contactMethod:"phone",idempotencyKey:"abcdefghij123",items:[{productId,quantity:"x".repeat(81),options:{Color:"Black"}}]},"ip1"),InquiryError);
await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"X",contact:"+251911234567",contactMethod:"phone",idempotencyKey:"abcdefghij12x",items:[{productId,quantity:{amount:1,unit:"ton"},options:{Color:"Black"}}]},"ip1x"),InquiryError);
await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"X",contact:"+251911234567",contactMethod:"phone",idempotencyKey:"abcdefghij124",items:[{productId,quantity:1,options:{Color:"Purple"}}]},"ip2"),InquiryError);
const first=await createPublicInquiry({businessId:a,customerName:"X",contact:"+251911234567",contactMethod:"phone",idempotencyKey:"abcdefghij125",items:[{productId,quantity:"20 cartons",options:{Color:"Black"}}]},"ip3");const second=await createPublicInquiry({businessId:a,customerName:"X",contact:"+251911234567",contactMethod:"phone",idempotencyKey:"abcdefghij125",items:[{productId,quantity:"20 cartons",options:{Color:"Black"}}]},"ip3");assert.equal(first.inquiryId,second.inquiryId);assert.equal(second.duplicate,true);db.prepare("UPDATE products SET availability='unavailable' WHERE id=?").run(productId);await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"X",contact:"+251911234567",contactMethod:"phone",idempotencyKey:"abcdefghij126",items:[{productId,quantity:"1 unit",options:{Color:"Black"}}]},"ip4"),InquiryError);
const capabilityId=Number(db.prepare("INSERT INTO products(business_id,category_id,name,slug,is_published,availability,offering_kind,quantity_mode) VALUES(?,?,?,'fabrication',1,'available','manufacturing_capability','optional')").run(a,catA,"Custom fabrication").lastInsertRowid);const capabilityInquiry=await createPublicInquiry({businessId:a,customerName:"Y",contact:"0911-234-567",contactMethod:"phone",idempotencyKey:"abcdefghij127",items:[{productId:capabilityId,quantity:null,options:{}}]},"ip5");const capabilityLine=db.prepare("SELECT quantity,quantity_intent,offering_kind_snapshot,quantity_mode_snapshot FROM inquiry_items WHERE inquiry_id=?").get(capabilityInquiry.inquiryId) as any;assert.deepEqual({...capabilityLine},{quantity:null,quantity_intent:"",offering_kind_snapshot:"manufacturing_capability",quantity_mode_snapshot:"optional"});
const inquiriesBeforeInvalidContact=Number((db.prepare("SELECT COUNT(*) count FROM inquiries").get() as any).count);await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"Visitor",contact:"visitor@example.test",contactMethod:"email",idempotencyKey:"abcdefghij128",items:[{productId:capabilityId,quantity:null,options:{}}]},"ip6"),/phone number is required/i);await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"Visitor",contact:"123",contactMethod:"phone",idempotencyKey:"abcdefghij129",items:[{productId:capabilityId,quantity:null,options:{}}]},"ip7"),/7 to 15 digits/i);assert.equal(Number((db.prepare("SELECT COUNT(*) count FROM inquiries").get() as any).count),inquiriesBeforeInvalidContact);
assert.throws(()=>verifyImage(Buffer.from("<html>bad</html>"),"text/html"),/Only valid/);const sharp=(await import("sharp")).default;assert.equal(sharp.versions.sharp,"0.35.3");const png=await sharp({create:{width:1,height:1,channels:4,background:{r:0,g:0,b:0,alpha:1}}}).png().toBuffer();assert.equal(verifyImage(png,"image/png").ext,"png");const saved=await saveUploadedImage(new File([new Uint8Array(png)],"safe.png",{type:"image/png"}),"","product");assert.match(saved,/^\/media\/product-/);await assert.rejects(()=>saveUploadedImage(new File([new TextEncoder().encode("<html>bad</html>")],"bad.html",{type:"text/html"}),"","product"),/Only valid/);
closeDbForTests();fs.rmSync(root,{recursive:true,force:true});console.log("Security integration tests passed.");

}
main().catch(error=>{console.error(error);process.exit(1)});
