import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import sharp from "sharp";

async function main(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"suqpage-revisions-"));process.env.SUQPAGE_DB_PATH=path.join(root,"revisions.db");process.env.SUQPAGE_MEDIA_ROOT=path.join(root,"media");try{const {getDb,getUserById,closeDbForTests,getCatalogByBusinessId}=await import("../lib/db");const {FileRequestAttachmentStore}=await import("../lib/request-media");const {createDraftRevision,saveDraftRevision,submitRevisionForReview,decideRevision,publishApprovedRevision,rollbackCatalogVersion,getContentRevision}=await import("../lib/revision-service");const {RevisionError}=await import("../lib/revision-domain");const {requireRevisionSnapshotV4}=await import("../lib/revision-v4-domain");const {SHOWROOM_COMPONENT_BANK_LATEST}=await import("../lib/showroom-bank-release");const parseRevisionSnapshot=(input:unknown)=>requireRevisionSnapshotV4(input,SHOWROOM_COMPONENT_BANK_LATEST);
  const businessId=Number(getDb().prepare("INSERT INTO businesses(handle,name,design_key,hero_title,status) VALUES('revision-market','Revision Market','novatech','Original live hero','active')").run().lastInsertRowid);const collectionId=Number(getDb().prepare("INSERT INTO collections(business_id,name,slug) VALUES(?,'Original collection','original')").run(businessId).lastInsertRowid);getDb().prepare("INSERT INTO products(business_id,collection_id,name,slug,description,is_published) VALUES(?,?,'Original product','original-product','Live description',1)").run(businessId,collectionId);
  const clientId=Number(getDb().prepare("INSERT INTO users(email,password_hash,name,role,business_id) VALUES('revision-client@test.local','unused','Revision Client','owner',?)").run(businessId).lastInsertRowid);getDb().prepare("INSERT INTO user_access_profiles(user_id,access_role) VALUES(?,'client')").run(clientId);const managerId=Number(getDb().prepare("INSERT INTO users(email,password_hash,name,role) VALUES('revision-manager@test.local','unused','Revision Manager','admin')").run().lastInsertRowid);getDb().prepare("INSERT INTO user_access_profiles(user_id,access_role) VALUES(?,'operations_manager')").run(managerId);const teamId=Number(getDb().prepare("INSERT INTO users(email,password_hash,name,role) VALUES('revision-team@test.local','unused','Revision Team','admin')").run().lastInsertRowid);getDb().prepare("INSERT INTO user_access_profiles(user_id,access_role) VALUES(?,'team_member')").run(teamId);const outsiderId=Number(getDb().prepare("INSERT INTO users(email,password_hash,name,role) VALUES('revision-outsider@test.local','unused','Other Team','admin')").run().lastInsertRowid);getDb().prepare("INSERT INTO user_access_profiles(user_id,access_role) VALUES(?,'team_member')").run(outsiderId);
  const requestId=Number(getDb().prepare("INSERT INTO service_requests(public_ref,business_id,represented_client_user_id,request_type,status,contact_name,contact_value,business_name,request_text,submitter_kind,submitted_by_user_id) VALUES('REQ-REVISION001',?,?,'change','in_progress','Revision Client','revision-client@test.local','Revision Market','Change the private hero and catalog.','client',?)").run(businessId,clientId,clientId).lastInsertRowid);getDb().prepare("UPDATE service_requests SET assigned_user_id=? WHERE id=?").run(teamId,requestId);getDb().prepare("INSERT INTO staff_business_assignments(user_id,business_id,assigned_by_user_id,active) VALUES(?,?,?,1)").run(teamId,businessId,managerId);
  const png=await sharp({create:{width:4,height:3,channels:4,background:{r:20,g:70,b:120,alpha:1}}}).png().toBuffer();const stored=await new FileRequestAttachmentStore().save({originalName:"client-hero.png",claimedType:"image/png",bytes:png});const attachmentId=Number(getDb().prepare("INSERT INTO request_attachments(request_id,storage_key,original_name,mime_type,byte_size,width,height) VALUES(?,?,?,?,?,?,?)").run(requestId,stored.storageKey,stored.originalName,stored.mime,stored.buffer.byteLength,stored.width,stored.height).lastInsertRowid);
  const client=getUserById(clientId)!,manager=getUserById(managerId)!,team=getUserById(teamId)!,outsider=getUserById(outsiderId)!;const draft=createDraftRevision(team,requestId);assert.equal(draft.revision_number,1);assert.equal(draft.base_content_version,1);assert.equal(parseRevisionSnapshot(draft.snapshot_json).schemaVersion,4);assert.throws(()=>createDraftRevision(outsider,requestId),(error:unknown)=>error instanceof RevisionError&&error.status===404);const snapshot=parseRevisionSnapshot(draft.snapshot_json);snapshot.business.heroTitle="Private revised hero";snapshot.business.heroImageRef=`request-attachment:${attachmentId}`;snapshot.products[0].name="Approved exact product";saveDraftRevision(team,draft.id,snapshot,"Updated hero and product name");submitRevisionForReview(team,draft.id);assert.throws(()=>saveDraftRevision(team,draft.id,snapshot,"tamper"),(error:unknown)=>error instanceof RevisionError&&error.status===409);assert.equal(getCatalogByBusinessId(businessId,true)!.business.hero_title,"Original live hero");assert.throws(()=>decideRevision(manager,draft.id,"approve",""),(error:unknown)=>error instanceof RevisionError&&error.status===403);decideRevision(client,draft.id,"reject","Please use a warmer hero treatment.");assert.equal(getContentRevision(draft.id)!.status,"rejected");assert.equal(getCatalogByBusinessId(businessId,true)!.products[0].name,"Original product");
  const second=createDraftRevision(team,requestId);assert.equal(second.revision_number,2);const secondSnapshot=parseRevisionSnapshot(second.snapshot_json);secondSnapshot.business.heroTitle="Approved private hero";saveDraftRevision(team,second.id,secondSnapshot,"Warmer approved treatment");submitRevisionForReview(team,second.id);decideRevision(client,second.id,"approve","Looks ready.");getDb().prepare("UPDATE businesses SET content_version=2 WHERE id=?").run(businessId);assert.throws(()=>publishApprovedRevision(manager,second.id),(error:unknown)=>error instanceof RevisionError&&error.status===409);assert.equal(getContentRevision(second.id)!.status,"approved");
  const third=createDraftRevision(team,requestId);const thirdSnapshot=parseRevisionSnapshot(third.snapshot_json);thirdSnapshot.business.heroTitle="Published approved hero";thirdSnapshot.products[0].name="Published exact product";saveDraftRevision(team,third.id,thirdSnapshot,"Final approved treatment");submitRevisionForReview(team,third.id);decideRevision(client,third.id,"approve","");const published=publishApprovedRevision(manager,third.id);assert.equal(published.contentVersion,3);const live=getCatalogByBusinessId(businessId,true)!;assert.equal(live.business.hero_title,"Published approved hero");assert.equal(live.products[0].name,"Published exact product");assert.match(live.business.hero_image_path,/^\/media\/revision-[0-9a-f-]{36}\.png$/);assert.equal(fs.existsSync(path.join(root,"media",path.basename(live.business.hero_image_path))),true);assert.equal((getDb().prepare("SELECT COUNT(*) count FROM published_catalog_versions WHERE business_id=?").get(businessId) as {count:number}).count,2);
  const rolledBack=rollbackCatalogVersion(manager,businessId,2);assert.equal(rolledBack.contentVersion,4);const restored=getCatalogByBusinessId(businessId,true)!;assert.equal(restored.business.hero_title,"Original live hero");assert.equal(restored.business.design_key,"composition");assert.doesNotThrow(()=>JSON.parse(restored.business.design_manifest_json));assert.doesNotThrow(()=>JSON.parse(restored.business.content_blocks_json));assert.equal(restored.business.content_version,4);assert.equal((getDb().prepare("SELECT COUNT(*) count FROM published_catalog_versions WHERE json_extract(snapshot_json,'$.schemaVersion')<>4").get() as {count:number}).count,0);assert.equal((getDb().prepare("SELECT COUNT(*) count FROM content_revisions WHERE snapshot_schema_version<>json_extract(snapshot_json,'$.schemaVersion')").get() as {count:number}).count,0);assert.deepEqual((getDb().prepare("SELECT version FROM schema_migrations ORDER BY version").all() as Array<{version:number}>).map((item)=>item.version),[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]);console.log("Schema-v4 revision approval, publication conflict, atomic composition replacement, and rollback tests passed.");closeDbForTests();}finally{fs.rmSync(root,{recursive:true,force:true});}}
main().catch((error)=>{console.error(error);process.exit(1)});
