import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";
async function main(){
const root=fs.mkdtempSync(path.join(os.tmpdir(),"suqpage-test-"));process.env.SUQPAGE_DB_PATH=path.join(root,"test.db");process.env.SUQPAGE_MEDIA_ROOT=path.join(root,"media");process.env.PRIVACY_SALT="test-privacy-salt-that-is-long-enough";process.env.NEXT_PUBLIC_APP_URL="https://suqpage.test";process.env.SUQPAGE_SERVER_ACTION_ORIGINS="http://127.0.0.1:4567";
const {getDb,closeDbForTests,getBusinessByHandle}=await import("../lib/db");const {assertSameOrigin}=await import("../lib/security");const {createPublicInquiry,InquiryError}=await import("../lib/inquiries");const {createDeliveryRequest,DeliveryError}=await import("../lib/deliveries");const {verifyImage,saveUploadedImage}=await import("../lib/media");const db=getDb();
const a=Number(db.prepare("INSERT INTO businesses(handle,name,design_key,status) VALUES('a','A','novatech','active')").run().lastInsertRowid),b=Number(db.prepare("INSERT INTO businesses(handle,name,design_key,status) VALUES('b','B','homevibe','draft')").run().lastInsertRowid);const ca=Number(db.prepare("INSERT INTO collections(business_id,name,slug) VALUES(?,?,'a')").run(a,"A").lastInsertRowid),cb=Number(db.prepare("INSERT INTO collections(business_id,name,slug) VALUES(?,?,'b')").run(b,"B").lastInsertRowid);const catA=Number(db.prepare("INSERT INTO categories(business_id,collection_id,name,slug) VALUES(?,?,?,'cat-a')").run(a,ca,"Cat A").lastInsertRowid);
assert.throws(()=>db.prepare("INSERT INTO products(business_id,collection_id,name,slug) VALUES(?,?,?,'bad')").run(a,cb,"Bad"),/does not belong/);
const productId=Number(db.prepare("INSERT INTO products(business_id,collection_id,category_id,name,slug,stock_count,is_published,availability) VALUES(?,?,?,?,?,5,1,'available')").run(a,ca,catA,"Phone","phone").lastInsertRowid);const groupId=Number(db.prepare("INSERT INTO option_groups(product_id,name,position) VALUES(?,? ,0)").run(productId,"Color").lastInsertRowid);db.prepare("INSERT INTO option_values(option_group_id,value,stock_count) VALUES(?,? ,5)").run(groupId,"Black");
assert.equal(getBusinessByHandle("b"),undefined);assert.doesNotThrow(()=>assertSameOrigin(new Request("https://suqpage.test/api/test",{headers:{origin:"https://suqpage.test"}})));assert.doesNotThrow(()=>assertSameOrigin(new Request("https://suqpage.test/api/test",{headers:{origin:"http://127.0.0.1:4567"}})));assert.throws(()=>assertSameOrigin(new Request("https://suqpage.test/api/test",{headers:{origin:"https://attacker.test"}})),/Invalid request origin/);
await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"X",contact:"12345",contactMethod:"phone",idempotencyKey:"abcdefghij123",items:[{productId,quantity:99,options:{Color:"Black"}}]},"ip1"),InquiryError);
await assert.rejects(()=>createPublicInquiry({businessId:a,customerName:"X",contact:"12345",contactMethod:"phone",idempotencyKey:"abcdefghij124",items:[{productId,quantity:1,options:{Color:"Purple"}}]},"ip2"),InquiryError);
const first=await createPublicInquiry({businessId:a,customerName:"X",contact:"12345",contactMethod:"phone",idempotencyKey:"abcdefghij125",items:[{productId,quantity:1,options:{Color:"Black"}}]},"ip3");const second=await createPublicInquiry({businessId:a,customerName:"X",contact:"12345",contactMethod:"phone",idempotencyKey:"abcdefghij125",items:[{productId,quantity:1,options:{Color:"Black"}}]},"ip3");assert.equal(first.inquiryId,second.inquiryId);assert.equal(second.duplicate,true);
const companyId=Number(db.prepare("INSERT INTO delivery_companies(name,slug) VALUES('Carrier','carrier')").run().lastInsertRowid);assert.throws(()=>createDeliveryRequest({businessId:b,customerName:"X",phone:"12345",pickupAddress:"A",deliveryAddress:"B",packageCount:1,companyIds:[companyId]},a,false),DeliveryError);
assert.throws(()=>verifyImage(Buffer.from("<html>bad</html>"),"text/html"),/Only valid/);const sharp=(await import("sharp")).default;assert.equal(sharp.versions.sharp,"0.35.3");const png=await sharp({create:{width:1,height:1,channels:4,background:{r:0,g:0,b:0,alpha:1}}}).png().toBuffer();assert.equal(verifyImage(png,"image/png").ext,"png");const saved=await saveUploadedImage(new File([new Uint8Array(png)],"safe.png",{type:"image/png"}),"","product");assert.match(saved,/^\/media\/product-/);await assert.rejects(()=>saveUploadedImage(new File([new TextEncoder().encode("<html>bad</html>")],"bad.html",{type:"text/html"}),"","product"),/Only valid/);
closeDbForTests();fs.rmSync(root,{recursive:true,force:true});console.log("Security integration tests passed.");

}
main().catch(error=>{console.error(error);process.exit(1)});
