import {
  BankCallToActionSection,
  BankCatalogSection,
  BankContentSection,
  BankFooterSection,
  BankHeaderSection,
  BankHeroSection,
  BankNavigationSection,
  BankTrustSection,
} from "./sections";
import type { BankRegistry } from "./types";

export const SHOWROOM_BANK_REGISTRY: BankRegistry = {
  "header.compact-utility@1": BankHeaderSection,
  "header.editorial-wordmark@1": BankHeaderSection,
  "header.catalog-command@1": BankHeaderSection,
  "header.transparent-overlay@1": BankHeaderSection,
  "header.producer-badge@1": BankHeaderSection,
  "hero.split-story@1": BankHeroSection,
  "hero.centered-statement@1": BankHeroSection,
  "hero.product-spotlight@1": BankHeroSection,
  "hero.editorial-collage@1": BankHeroSection,
  "hero.material-detail@1": BankHeroSection,
  "hero.provenance@1": BankHeroSection,
  "hero.industrial-spec@1": BankHeroSection,
  "hero.collection-mosaic@1": BankHeroSection,
  "navigation.category-pills@1": BankNavigationSection,
  "navigation.collection-rail@1": BankNavigationSection,
  "navigation.catalog-index@1": BankNavigationSection,
  "navigation.minimal-tabs@1": BankNavigationSection,
  "content.origin-story@1": BankContentSection,
  "content.process-steps@1": BankContentSection,
  "content.material-focus@1": BankContentSection,
  "content.founder-note@1": BankContentSection,
  "content.production-metrics@1": BankContentSection,
  "content.editorial-quote@1": BankContentSection,
  "catalog.editorial-grid@1": BankCatalogSection,
  "catalog.dense-wholesale@1": BankCatalogSection,
  "catalog.feature-tiles@1": BankCatalogSection,
  "catalog.horizontal-shelf@1": BankCatalogSection,
  "catalog.collection-led@1": BankCatalogSection,
  "catalog.minimal-list@1": BankCatalogSection,
  "trust.product-details@1": BankTrustSection,
  "trust.provenance-panel@1": BankTrustSection,
  "trust.business-principles@1": BankTrustSection,
  "trust.wholesale-readiness@1": BankTrustSection,
  "trust.care-guide@1": BankTrustSection,
  "call-to-action.inquiry@1": BankCallToActionSection,
  "call-to-action.wholesale@1": BankCallToActionSection,
  "call-to-action.sample-question@1": BankCallToActionSection,
  "call-to-action.consultation@1": BankCallToActionSection,
  "footer.compact@1": BankFooterSection,
  "footer.editorial@1": BankFooterSection,
  "footer.catalog-directory@1": BankFooterSection,
  "footer.contact-panel@1": BankFooterSection,
};
