import type { BankTokenStyle } from "./types";

export const SHOWROOM_BANK_TOKEN_STYLES = {
  "linen-luxury": {
    id: "linen-luxury",
    label: "Linen luxury",
    variables: {
      "--bank-bg": "#f6f0e6",
      "--bank-surface": "#fffaf2",
      "--bank-ink": "#29231d",
      "--bank-muted": "#74685c",
      "--bank-accent": "#8b5e3c",
      "--bank-accent-soft": "#ead8c4",
      "--bank-line": "#d8c8b7",
      "--bank-radius": "22px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "harvest-earth": {
    id: "harvest-earth",
    label: "Harvest earth",
    variables: {
      "--bank-bg": "#f2efe2",
      "--bank-surface": "#fbf9ef",
      "--bank-ink": "#263526",
      "--bank-muted": "#66705d",
      "--bank-accent": "#53723f",
      "--bank-accent-soft": "#dbe5c9",
      "--bank-line": "#cdd5bf",
      "--bank-radius": "18px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "honey-amber": {
    id: "honey-amber",
    label: "Honey amber",
    variables: {
      "--bank-bg": "#fff7dc",
      "--bank-surface": "#fffdf4",
      "--bank-ink": "#3a2912",
      "--bank-muted": "#7b6544",
      "--bank-accent": "#b96f08",
      "--bank-accent-soft": "#f8df9d",
      "--bank-line": "#e5c982",
      "--bank-radius": "26px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "coffee-roast": {
    id: "coffee-roast",
    label: "Coffee roast",
    variables: {
      "--bank-bg": "#211a17",
      "--bank-surface": "#30251f",
      "--bank-ink": "#f8eee2",
      "--bank-muted": "#c7b3a2",
      "--bank-accent": "#d18d52",
      "--bank-accent-soft": "#5a3c2c",
      "--bank-line": "#58483e",
      "--bank-radius": "14px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "artisan-clay": {
    id: "artisan-clay",
    label: "Artisan clay",
    variables: {
      "--bank-bg": "#f4e7df",
      "--bank-surface": "#fff8f2",
      "--bank-ink": "#3a2825",
      "--bank-muted": "#80665f",
      "--bank-accent": "#a9553f",
      "--bank-accent-soft": "#eac1b3",
      "--bank-line": "#d9b8ae",
      "--bank-radius": "34px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "forest-botanical": {
    id: "forest-botanical",
    label: "Forest botanical",
    variables: {
      "--bank-bg": "#12251f",
      "--bank-surface": "#1b332b",
      "--bank-ink": "#eff8ef",
      "--bank-muted": "#adc4b7",
      "--bank-accent": "#8ccf85",
      "--bank-accent-soft": "#315a45",
      "--bank-line": "#426456",
      "--bank-radius": "20px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "furniture-walnut": {
    id: "furniture-walnut",
    label: "Furniture walnut",
    variables: {
      "--bank-bg": "#eee8df",
      "--bank-surface": "#faf7f2",
      "--bank-ink": "#292622",
      "--bank-muted": "#706960",
      "--bank-accent": "#704b34",
      "--bank-accent-soft": "#d8c6b5",
      "--bank-line": "#cfc5b9",
      "--bank-radius": "8px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "industrial-steel": {
    id: "industrial-steel",
    label: "Industrial steel",
    variables: {
      "--bank-bg": "#e9edf0",
      "--bank-surface": "#f9fafb",
      "--bank-ink": "#182127",
      "--bank-muted": "#59666e",
      "--bank-accent": "#d85b32",
      "--bank-accent-soft": "#f0c5b6",
      "--bank-line": "#bfc8ce",
      "--bank-radius": "2px",
      "--bank-display": "Arial, Helvetica, sans-serif",
    },
  },
  "maker-indigo": {
    id: "maker-indigo",
    label: "Maker indigo",
    variables: {
      "--bank-bg": "#edf0f8",
      "--bank-surface": "#fdfdff",
      "--bank-ink": "#19203c",
      "--bank-muted": "#626b8a",
      "--bank-accent": "#4056b8",
      "--bank-accent-soft": "#ccd4fa",
      "--bank-line": "#c5cbe0",
      "--bank-radius": "16px",
      "--bank-display": "Arial, Helvetica, sans-serif",
    },
  },
  "ocean-trade": {
    id: "ocean-trade",
    label: "Ocean trade",
    variables: {
      "--bank-bg": "#e9f3f4",
      "--bank-surface": "#fbffff",
      "--bank-ink": "#12323b",
      "--bank-muted": "#54727a",
      "--bank-accent": "#087a8b",
      "--bank-accent-soft": "#bce4e7",
      "--bank-line": "#b7d1d4",
      "--bank-radius": "12px",
      "--bank-display": "Arial, Helvetica, sans-serif",
    },
  },
  "beauty-editorial": {
    id: "beauty-editorial",
    label: "Beauty editorial",
    variables: {
      "--bank-bg": "#fff1f6",
      "--bank-surface": "#fffafd",
      "--bank-ink": "#361e2b",
      "--bank-muted": "#876779",
      "--bank-accent": "#c13f78",
      "--bank-accent-soft": "#f2c6da",
      "--bank-line": "#e5c3d3",
      "--bank-radius": "28px",
      "--bank-display": "Georgia, 'Times New Roman', serif",
    },
  },
  "technology-mono": {
    id: "technology-mono",
    label: "Technology mono",
    variables: {
      "--bank-bg": "#f2f3f5",
      "--bank-surface": "#ffffff",
      "--bank-ink": "#101114",
      "--bank-muted": "#666970",
      "--bank-accent": "#1517d3",
      "--bank-accent-soft": "#d8d9ff",
      "--bank-line": "#d3d5db",
      "--bank-radius": "10px",
      "--bank-display": "Arial, Helvetica, sans-serif",
    },
  },
  "vibrant-market": {
    id: "vibrant-market",
    label: "Vibrant market",
    variables: {
      "--bank-bg": "#fff5d8",
      "--bank-surface": "#ffffff",
      "--bank-ink": "#17223a",
      "--bank-muted": "#68728a",
      "--bank-accent": "#ef4e2f",
      "--bank-accent-soft": "#ffd2a6",
      "--bank-line": "#e2cfaa",
      "--bank-radius": "20px",
      "--bank-display": "Arial, Helvetica, sans-serif",
    },
  },
} as const satisfies Record<string, BankTokenStyle>;

export type ShowroomBankTokenId = keyof typeof SHOWROOM_BANK_TOKEN_STYLES;
